/**
 * OmniJinja VS Code Extension
 *
 * This module orchestrates the frontend language server features for Jinja2 templates.
 * It acts as the bridge between VS Code's Extension API and the Python-based OmniJinja
 * analysis engine. Features include intelligent auto-completion, hover documentation,
 * go-to-definition, real-time diagnostics (linting), and automated Quick Fixes.
 */

import * as vscode from 'vscode';
import { exec, execSync } from 'child_process';
import * as path from 'path';
import * as fs from 'fs';

// Import built-in Jinja2 definitions (tags, filters, tests, globals)
import { BUILTIN_FILTERS, BUILTIN_TAGS, BUILTIN_TESTS, BUILTIN_GLOBALS } from './jinja_builtins';

// ==========================================
// Memory Registries (State Management)
// ==========================================

/** * Caches context data passed from Python views to templates.
 * Map structure: Template Name -> Map<Python Source Path, Context Variables>
 */
const templateRegistry = new Map<string, Map<string, any>>();

/** * Caches custom Flask filters extracted from Python code.
 * Map structure: Python Source Path -> Array of Filter Metadata
 */
const filterRegistry = new Map<string, any[]>();

/** * Caches template files referenced within Python files.
 * Map structure: Python Source Path -> Set of Template Paths
 */
const templateFilesRegistry = new Map<string, Set<string>>();

/** * Caches local variables defined within the Jinja template itself (e.g., via {% set %}).
 * Map structure: Template Name -> Local Context Variables
 */
const internalJinjaRegistry = new Map<string, any>();

/** * Caches external requirements (Demand) parsed from Jinja templates.
 * Map structure: Template Name -> Requirements JSON Object
 */
const externalRequirementsRegistry = new Map<string, any>();

/** * Caches raw render calls (Supply) from Python files specifically for validation.
 * Map structure: Python Source Path -> Array of Render Calls
 */
const renderCallRegistry = new Map<string, any[]>();

/** Collection to render squiggly lines inside Python files */
let pyDiagnosticCollection: vscode.DiagnosticCollection;

/** * Caches the fully repaired source code generated by the Python fixer engine.
 * Map structure: HTML File Path -> Repaired Source Code String
 */
const fixedCodeRegistry = new Map<string, string>();

// Cache to store unique identifiers for ignored diagnostics
const ignoredDiagnosticsCache = new Set<string>();

/** * Caches template dependencies (extends, includes, imports) to build inheritance trees.
 * Map structure: Template Name -> { extends?: string, includes?: string[], imports?: any[] }
 */
const templateDependenciesRegistry = new Map<string, any>();

/** * Caches block names inherited from parent templates and available for override.
 * Map structure: Template Name -> Array of Block Names
 */
const templateBlocksRegistry = new Map<string, string[]>();

// Background task queues and debounce timers for performance optimization
const debounceTimers = new Map<string, NodeJS.Timeout>();
const parseQueue: string[] = [];
let isParsing = false;
const jinjaParseQueue: string[] = [];
let isJinjaParsing = false;

/** Collection to manage and render wavy underlines for syntax errors and warnings */
let diagnosticCollection: vscode.DiagnosticCollection;

const COMPLETION_TRIGGER_CHARS = [
    '{', ' ', '|', '.', 's'
];



function getTemplateKey(absolutePath: string): string {
    const normalized = absolutePath.replace(/\\/g, '/');
    const match = normalized.match(/\/templates\/(.+)$/);
    return match ? match[1] : path.basename(absolutePath);
}

function getSafePyName(absolutePath: string, workspaceRoot: string): string {
    const relative = path.relative(workspaceRoot, absolutePath);
    return relative.replace(/\\/g, '_').replace(/\//g, '_') + "_schema.json";
}

function getSafeJinjaName(absolutePath: string, workspaceRoot: string): string {
    const relative = path.relative(workspaceRoot, absolutePath);
    return relative.replace(/\\/g, '_').replace(/\//g, '_') + "_jinja.json";
}


/**
 * Formats a variable's internal schema into a human-readable type string for the UI.
 * * @param val - The variable schema object extracted by the Python backend.
 * @returns A formatted type string (e.g., "Iterable[Order]" or "String").
 */
function getDisplayType(val: any): string {
    if (typeof val === 'string') return val;
    if (Array.isArray(val)) {
        if (val.length > 0 && val[0] && val[0].__type__) return `Iterable[${val[0].__type__}]`;
        return 'Iterable';
    }
    if (val && typeof val === 'object') {
        if (val.__is_iterable__) {
            if (val.__element__) return `${val.__type__}[${val.__element__.__type__ || 'Object'}]`;
            return `${val.__type__}[...]`;
        }
        return val.__type__ || 'Object';
    }
    return 'Unknown';
}

/**
 * Creates a formatted Markdown hover tooltip for built-in Jinja constructs.
 * * @param type - The construct category (e.g., 'tag', 'filter', 'test').
 * @param signature - The structural signature of the construct.
 * @param desc - Detailed explanation of what the construct does.
 * @param caveat - Optional edge-case warnings or important notes.
 * @returns A complete vscode.Hover object ready for rendering.
 */
function createBuiltinHover(type: string, signature: string, desc: string, caveat?: string): vscode.Hover {
    const md = new vscode.MarkdownString();
    md.appendCodeblock(`(${type}) Usage: ${signature}`, 'python');
    md.appendMarkdown(`\n---\n${desc}`);
    if (caveat) md.appendMarkdown(`\n\n*💡 **Caveat**: ${caveat}*`);
    return new vscode.Hover(md);
}

/**
 * Generates a unique key for a diagnostic based on file path, line, and message.
 * This helps identify which specific warning to suppress.
 */
function getDiagnosticKey(uri: vscode.Uri, line: number, message: string): string {
    return `${uri.fsPath}|${line}|${message}`;
}

function mergeSchema(target: any, source: any) {
    if (!source || typeof source !== 'object') {
        return target;
    }
    for (const [key, value] of Object.entries(source)) {
        target[key] = value;
    }
    return target;
}

function normalizeTemplateName(templateName: string) {
    return templateName.replace(/\\/g, '/');
}

function findTemplateKey<T>(registry: Map<string, T>, templateName: string) {
    const normalized = normalizeTemplateName(templateName);
    if (registry.has(normalized)) {
        return normalized;
    }

    const basename = path.basename(normalized);
    if (registry.has(basename)) {
        return basename;
    }

    for (const key of registry.keys()) {
        if (path.basename(key) === basename) {
            return key;
        }
    }
    for (const key of registry.keys()) {
        const normalizedKey = normalizeTemplateName(key);
        if (normalizedKey.endsWith(`/${normalized}`) || normalized.endsWith(`/${normalizedKey}`)) {
            return key;
        }
    }
    return normalized;
}

function getRegistryValue<T>(registry: Map<string, T>, templateName: string) {
    return registry.get(findTemplateKey(registry, templateName));
}

function getCompletionChildren(schemaNode: any) {
    if (!schemaNode || typeof schemaNode !== 'object') {
        return undefined;
    }
    if (schemaNode.__is_iterable__ && schemaNode.__element__ && typeof schemaNode.__element__ === 'object') {
        return schemaNode.__element__;
    }
    return schemaNode;
}

function getBackendContextForTemplate(templateName: string) {
    const context: any = {};
    const templateKey = findTemplateKey(templateRegistry, templateName);
    const sources = templateRegistry.get(templateKey);
    if (!sources) {
        return context;
    }

    for (const sourceContext of sources.values()) {
        mergeSchema(context, sourceContext);
    }
    return context;
}

function getInternalExportsForTemplate(templateName: string) {
    const exports: any = {};
    const templateKey = findTemplateKey(internalJinjaRegistry, templateName);
    const internal = internalJinjaRegistry.get(templateKey);
    if (!internal) {
        return exports;
    }

    if (internal.globals) {
        mergeSchema(exports, internal.globals);
    }

    for (const [key, value] of Object.entries(internal)) {
        if (!['globals', 'scoped', 'dependencies'].includes(key)) {
            exports[key] = value;
        }
    }
    return exports;
}

function getInheritedBackendContext(templateName: string) {
    const inheritedContext: any = {};
    const visited = new Set<string>();

    function visit(currentTemplate: string) {
        const currentTemplateKey = findTemplateKey(templateDependenciesRegistry, currentTemplate);
        const deps = templateDependenciesRegistry.get(currentTemplateKey);
        const parentTemplate = deps?.extends;
        if (!parentTemplate || visited.has(parentTemplate)) {
            return;
        }

        visited.add(parentTemplate);
        visit(parentTemplate);
        mergeSchema(inheritedContext, getBackendContextForTemplate(parentTemplate));
        mergeSchema(inheritedContext, getInternalExportsForTemplate(parentTemplate));
    }

    visit(templateName);
    return inheritedContext;
}

function getEffectiveBackendContext(templateName: string) {
    const context = getInheritedBackendContext(templateName);
    mergeSchema(context, getBackendContextForTemplate(templateName));
    mergeSchema(context, getInternalExportsForTemplate(templateName));
    return context;
}

function getOverridableBlocksForTemplate(templateName: string) {
    const templateKey = findTemplateKey(templateBlocksRegistry, templateName);
    return templateBlocksRegistry.get(templateKey) || [];
}

function hasKnownSchemaChildren(schemaNode: any) {
    if (!schemaNode || typeof schemaNode !== 'object' || Array.isArray(schemaNode)) {
        return false;
    }

    const metadataKeys = new Set(['def_line', 'args', 'signature', 'docstring', 'error']);
    return Object.keys(schemaNode).some(key => !key.startsWith('__') && !metadataKeys.has(key));
}

function isGenericSchemaLeaf(schemaNode: any) {
    return !!schemaNode && typeof schemaNode === 'object' && '__type__' in schemaNode && !hasKnownSchemaChildren(schemaNode);
}

function getSchemaChild(schemaNode: any, key: string) {
    if (!schemaNode || typeof schemaNode !== 'object') {
        return undefined;
    }
    if (key in schemaNode) {
        return schemaNode[key];
    }
    const elementSchema = schemaNode.__element__;
    if (elementSchema && typeof elementSchema === 'object' && key in elementSchema) {
        return elementSchema[key];
    }
    return undefined;
}

function isRequirementSatisfied(requirementNode: any, schemaNode: any): boolean {
    if (schemaNode === undefined || schemaNode === null) {
        return false;
    }
    if (!requirementNode || typeof requirementNode !== 'object' || !schemaNode || typeof schemaNode !== 'object') {
        return true;
    }

    if (requirementNode.__is_callable__) {
        const schemaType = schemaNode.__type__;
        if (schemaType && !['Function', 'Method', 'Macro', 'Any'].includes(schemaType)) {
            return false;
        }
    }

    if (requirementNode.__is_iterable__) {
        const schemaType = schemaNode.__type__;
        const isIterable = schemaNode.__is_iterable__ || ['Iterable', 'List', 'Tuple', 'Dict', 'Any'].includes(schemaType);
        if (!isIterable) {
            return false;
        }
    }

    const childKeys = Object.keys(requirementNode).filter(key => !key.startsWith('__'));
    if (childKeys.length === 0) {
        return true;
    }

    if (isGenericSchemaLeaf(schemaNode)) {
        return true;
    }

    return childKeys.every(key => {
        const childSchema = getSchemaChild(schemaNode, key);
        return childSchema !== undefined && isRequirementSatisfied(requirementNode[key], childSchema);
    });
}

function pruneRequirementsSatisfiedBySchema(requirements: any, schema: any): any {
    if (!requirements || typeof requirements !== 'object' || !schema || typeof schema !== 'object') {
        return requirements || {};
    }

    const pruned: any = {};
    for (const [key, requirement] of Object.entries(requirements)) {
        if (key.startsWith('__')) {
            pruned[key] = requirement;
            continue;
        }

        const schemaNode = getSchemaChild(schema, key);
        if (isRequirementSatisfied(requirement, schemaNode)) {
            continue;
        }

        if (requirement && typeof requirement === 'object' && schemaNode && typeof schemaNode === 'object') {
            const nested = pruneRequirementsSatisfiedBySchema(requirement, schemaNode);
            if (Object.keys(nested).length > 0) {
                pruned[key] = nested;
            }
        } else {
            pruned[key] = requirement;
        }
    }
    return pruned;
}

function buildEffectiveExternalRequirements(templateName: string) {
    const templateKey = findTemplateKey(externalRequirementsRegistry, templateName);
    const demand = externalRequirementsRegistry.get(templateKey);
    if (!demand) {
        return undefined;
    }

    const inheritedContext = getInheritedBackendContext(templateKey);
    return pruneRequirementsSatisfiedBySchema(demand, inheritedContext);
}

function resolveSchemaPath(context: any, pathParts: string[]) {
    if (!context || pathParts.length === 0) {
        return undefined;
    }

    let current = context[pathParts[0]];
    for (const part of pathParts.slice(1)) {
        if (isGenericSchemaLeaf(current)) {
            return current;
        }
        const child = getSchemaChild(current, part);
        if (child === undefined) {
            return undefined;
        }
        current = child;
    }
    return current;
}

function diagnosticIsSatisfiedByEffectiveContext(message: string, templateName: string) {
    const context = getEffectiveBackendContext(templateName);
    const undefinedMatch = message.match(/Undefined Warning:\s*'([^']+)'/);
    if (undefinedMatch) {
        return resolveSchemaPath(context, [undefinedMatch[1]]) !== undefined;
    }

    const propertyMatch = message.match(/Property Warning:\s*'([^']+)'\s+is not a known property of\s+'([^']+)'/);
    if (propertyMatch) {
        return resolveSchemaPath(context, [...propertyMatch[2].split('.'), propertyMatch[1]]) !== undefined;
    }

    return false;
}

// ==========================================
// Code Action Provider (Lightbulb Quick Fix)
// ==========================================

/**
 * Provides automated Quick Fix actions for detected Jinja syntax errors.
 * It retrieves the pre-calculated repaired code from the `fixedCodeRegistry`.
 */
export class OmniJinjaFixer implements vscode.CodeActionProvider {
    public provideCodeActions(
        document: vscode.TextDocument,
        range: vscode.Range | vscode.Selection,
        context: vscode.CodeActionContext,
        token: vscode.CancellationToken
    ): vscode.ProviderResult<(vscode.CodeAction | vscode.Command)[]> {

        const actions: vscode.CodeAction[] = [];

        for (const diagnostic of context.diagnostics) {
            if (diagnostic.source === 'OmniJinja') {

                if (diagnostic.severity === vscode.DiagnosticSeverity.Error) {
                    const fixedCode = fixedCodeRegistry.get(document.uri.fsPath);
                    if (fixedCode) {
                        const fixAction = new vscode.CodeAction('Fix Jinja Syntax Error (OmniJinja)', vscode.CodeActionKind.QuickFix);
                        fixAction.edit = new vscode.WorkspaceEdit();
                        const fullRange = new vscode.Range(document.positionAt(0), document.positionAt(document.getText().length));
                        fixAction.edit.replace(document.uri, fullRange, fixedCode);
                        actions.push(fixAction);
                    }
                }

                // Provide "Ignore" action for Warnings (Yellow squiggly lines)
                if (diagnostic.severity === vscode.DiagnosticSeverity.Warning) {
                    const ignoreAction = new vscode.CodeAction('Ignore this warning (Locally)', vscode.CodeActionKind.QuickFix);
                    ignoreAction.command = {
                        title: 'Ignore Locally',
                        command: 'omnijinja.ignoreDiagnostic',
                        arguments: [document.uri, diagnostic]
                    };

                    actions.push(ignoreAction);
                }
            }
        }

        return actions;
    }
}

// ==========================================
// Extension Activation & Lifecycle
// ==========================================

let activePythonCmd = 'python';

async function resolvePythonPath(): Promise<string | undefined> {
    const config = vscode.workspace.getConfiguration('omnijinja');
    const customPath = config.get<string>('pythonPath');
    if (customPath && customPath.trim() !== '') return customPath;

    const commands = ['python3', 'python'];
    for (const cmd of commands) {
        try {
            execSync(`${cmd} --version`, { stdio: 'ignore', timeout: 1000 });
            return cmd;
        } catch (e) {
            continue;
        }
    }
    return undefined;
}


export async function activate(context: vscode.ExtensionContext) {
    console.log('🚀 OmniJinja activated successfully!');

    const resolvedCmd = await resolvePythonPath();
    if (!resolvedCmd) {
        vscode.window.showErrorMessage(
            "OmniJinja: Unable to find Python environment (python or python3). Please ensure that Python is installed, or manually specify the path in settings.",
            "Open Settings"
        ).then(selection => {
            if (selection === "Open Settings") {
                vscode.commands.executeCommand('workbench.action.openSettings', 'omnijinja.pythonPath');
            }
        });
        return;
    }
    activePythonCmd = resolvedCmd;

    diagnosticCollection = vscode.languages.createDiagnosticCollection('omnijinja');
    context.subscriptions.push(diagnosticCollection);

    // Initialize Python diagnostics
    pyDiagnosticCollection = vscode.languages.createDiagnosticCollection('omnijinja-python');
    context.subscriptions.push(pyDiagnosticCollection);

    const workspaceRoot = vscode.workspace.workspaceFolders?.[0].uri.fsPath;
    if (!workspaceRoot) {
        vscode.window.showInformationMessage(
            "OmniJinja: Please open a folder (workspace) to enable Python-Jinja data flow analysis."
        );
        return;
    }

    let storagePath = context.storageUri?.fsPath;
    if (!storagePath) {
        // Fallback to global storage if workspace storage isn't available
        storagePath = context.globalStorageUri.fsPath;
    }

    // Ensure our hidden schema directories exist before Python tries to write to them
    const backendDir = path.join(storagePath, 'backend_schemas');
    const jinjaDir = path.join(storagePath, 'jinja_schemas');
    if (!fs.existsSync(backendDir)) fs.mkdirSync(backendDir, { recursive: true });
    if (!fs.existsSync(jinjaDir)) fs.mkdirSync(jinjaDir, { recursive: true });

    const pythonEnginePath = path.join(context.extensionPath, 'python_engine');

    const supportedLanguages = ['html', 'jinja', 'jinja-html', 'jinja2'];

    // Register the Quick Fix Code Action Provider
    context.subscriptions.push(
        vscode.languages.registerCodeActionsProvider(
            supportedLanguages,
            new OmniJinjaFixer(),
            { providedCodeActionKinds: [vscode.CodeActionKind.QuickFix] }
        )
    );

    // Initial workspace scan
    vscode.window.withProgress({
        location: vscode.ProgressLocation.Window,
        title: "OmniJinja: Loading Cache & Initializing...",
    }, async (progress) => {
        const pyFiles = await vscode.workspace.findFiles('**/*.py', '**/{node_modules,.venv,venv}/**');

        for (const file of pyFiles) {
            loadSchemaIntoMemory(file.fsPath, workspaceRoot, storagePath, pythonEnginePath);
        }

        const templatePatterns = ['**/*.html', '**/*.jinja', '**/*.j2', '**/*.jinja2'];
        const excludePattern = '**/{node_modules,.venv,venv}/**';
        const allTemplateFiles: vscode.Uri[] = [];

        for (const pattern of templatePatterns) {
            const templateFiles = await vscode.workspace.findFiles(pattern, excludePattern);
            for (const file of templateFiles) {
                allTemplateFiles.push(file);
                loadJinjaSchemaIntoMemory(file.fsPath, workspaceRoot, storagePath);
            }
        }

        for (const file of pyFiles) {
            parseQueue.push(file.fsPath);
        }
        for (const file of allTemplateFiles) {
            jinjaParseQueue.push(file.fsPath);
        }

        processQueue(pythonEnginePath, workspaceRoot, storagePath);
        processJinjaQueue(pythonEnginePath, workspaceRoot, storagePath);
    });

    // Real-time File Change Listeners for Instant Reprocessing
    const pyChangeListener = vscode.workspace.onDidChangeTextDocument((event) => {
        const document = event.document;
        if (document.languageId === 'python') {
            const filePath = document.uri.fsPath;
            if (debounceTimers.has(filePath)) clearTimeout(debounceTimers.get(filePath)!);
            debounceTimers.set(filePath, setTimeout(() => {
                if (!parseQueue.includes(filePath)) {
                    parseQueue.push(filePath);
                    processQueue(pythonEnginePath, workspaceRoot, storagePath);
                }
                debounceTimers.delete(filePath);
            }, 300));
        }
    });

    const htmlChangeListener = vscode.workspace.onDidChangeTextDocument((event) => {
        const document = event.document;
        const validLangs = ['html', 'jinja', 'django-html', 'jinja-html'];
        if (validLangs.includes(document.languageId) || document.fileName.endsWith('.html')) {
            const filePath = document.uri.fsPath;
            if (debounceTimers.has(filePath)) clearTimeout(debounceTimers.get(filePath)!);
            debounceTimers.set(filePath, setTimeout(() => {
                if (!jinjaParseQueue.includes(filePath)) {
                    jinjaParseQueue.push(filePath);
                    processJinjaQueue(pythonEnginePath, workspaceRoot, storagePath);
                }
                debounceTimers.delete(filePath);
            }, 300));
        }
    });

    // File Deletion Watchers to Clean Up Memory
    const watcher = vscode.workspace.createFileSystemWatcher('**/*.py');
    watcher.onDidDelete((uri) => {
        const deletedPyPath = uri.fsPath;
        const safeName = getSafePyName(deletedPyPath, workspaceRoot);
        const jsonPath = path.join(storagePath, 'backend_schemas', safeName);
        if (fs.existsSync(jsonPath)) fs.unlinkSync(jsonPath);

        for (const [templateName, sourceMap] of templateRegistry.entries()) {
            if (sourceMap.has(deletedPyPath)) {
                sourceMap.delete(deletedPyPath);
                if (sourceMap.size === 0) templateRegistry.delete(templateName);
            }
        }
        if (filterRegistry.has(deletedPyPath)) filterRegistry.delete(deletedPyPath);
        if (templateFilesRegistry.has(deletedPyPath)) templateFilesRegistry.delete(deletedPyPath);
    });

    const htmlWatcher = vscode.workspace.createFileSystemWatcher('**/*.{html,jinja,j2,jinja2}');

    htmlWatcher.onDidDelete((uri) => {
        const deletedHtmlPath = uri.fsPath;
        const templateKey = getTemplateKey(deletedHtmlPath);
        const safeName = getSafeJinjaName(deletedHtmlPath, workspaceRoot);

        diagnosticCollection.delete(uri);
        internalJinjaRegistry.delete(templateKey);
        templateDependenciesRegistry.delete(templateKey);
        templateBlocksRegistry.delete(templateKey);
        fixedCodeRegistry.delete(deletedHtmlPath);
        externalRequirementsRegistry.delete(templateKey);

        const jsonPath = path.join(storagePath, 'jinja_schemas', safeName);
        if (fs.existsSync(jsonPath)) fs.unlinkSync(jsonPath);
    });

    // ==========================================
    // Unified Context Builder (Recursive Dependency Resolver)
    // ==========================================

    function buildStrictContext(document: vscode.TextDocument, position: vscode.Position) {
        const currentHtmlName = getTemplateKey(document.fileName);
        const mergedContext: any = {};
        const activeLine = position.line + 1;

        const visitedTemplates = new Set<string>();

        function mergeContextRecursively(templateName: string, isRoot: boolean) {
            if (visitedTemplates.has(templateName)) return;
            visitedTemplates.add(templateName);

            const getTemplateExports = (tplName: string) => {
                const exports: any = {};
                const internal = getRegistryValue(internalJinjaRegistry, tplName);
                if (internal) {
                    for (const key in internal) {
                        if (key !== 'globals' && key !== 'scoped' && key !== 'dependencies') {
                            exports[key] = internal[key];
                        }
                    }
                    if (internal.globals) {
                        for (const key in internal.globals) {
                            exports[key] = internal.globals[key];
                        }
                    }
                }
                return exports;
            };

            const deps = getRegistryValue(templateDependenciesRegistry, templateName);
            if (deps) {
                // {% extends '...' %}
                if (deps.extends) {
                    mergeContextRecursively(deps.extends, false);
                }
                // {% include '...' %}
                if (deps.includes) {
                    for (const inc of deps.includes) {
                        mergeContextRecursively(inc, false);
                    }
                }
                // {% import ... %} 和 {% from ... import ... %}
                if (deps.imports) {
                    for (const imp of deps.imports) {
                        const targetTpl = imp.template;
                        const exportedSymbols = getTemplateExports(targetTpl);

                        if (imp.type === 'import' && imp.namespace) {
                            mergedContext[imp.namespace] = {
                                __type__: "Module",
                                __is_iterable__: false,
                                ...exportedSymbols
                            };
                        } else if (imp.type === 'from_import' && imp.names) {
                            for (const [originalName, alias] of Object.entries(imp.names)) {
                                if (exportedSymbols[originalName]) {
                                    mergedContext[alias as string] = exportedSymbols[originalName];
                                } else {
                                    mergedContext[alias as string] = { __type__: "Macro/Any" };
                                }
                            }
                        }
                    }
                }
            }

            const pySourcesMap = getRegistryValue(templateRegistry, templateName);
            if (pySourcesMap) {
                for (const ctx of pySourcesMap.values()) Object.assign(mergedContext, ctx);
            }

            const internalCtx = getRegistryValue(internalJinjaRegistry, templateName);
            if (internalCtx) {
                // A. Globals (e.g., {% set %})
                if (internalCtx.globals) {
                    for (const [varName, varInfo] of Object.entries(internalCtx.globals)) {
                        const defLine = (varInfo as any).def_line || 0;
                        if (!isRoot || activeLine >= defLine) {
                            mergedContext[varName] = varInfo;
                        }
                    }
                }

                // B. Scoped (e.g., {% for %})
                if (isRoot && internalCtx.scoped) {
                    for (const scope of internalCtx.scoped) {
                        if (activeLine >= scope.scope_range.start_line && activeLine <= scope.scope_range.end_line) {
                            Object.assign(mergedContext, scope.vars);
                        }
                    }
                }

                // C. Macros
                for (const key in internalCtx) {
                    if (key !== 'globals' && key !== 'scoped' && key !== 'dependencies') {
                        mergedContext[key] = internalCtx[key];
                    }
                }
            }
        }

        mergeContextRecursively(currentHtmlName, true);
        mergeLiveLoopContext(document, position, mergedContext);
        return mergedContext;
    }

    function mergeLiveLoopContext(document: vscode.TextDocument, position: vscode.Position, context: any) {
        const prefixRange = new vscode.Range(new vscode.Position(0, 0), position);
        const textBeforeCursor = document.getText(prefixRange);
        const lines = textBeforeCursor.split(/\r?\n/);
        const loopStack: Array<{ names: string[] }> = [];

        for (const line of lines) {
            const tagPattern = /\{%-?\s*(for\s+.+?\s+in\s+[a-zA-Z_][\w.]*|endfor)\s*-?%\}/g;
            let match: RegExpExecArray | null;
            while ((match = tagPattern.exec(line)) !== null) {
                const tagContent = match[1].trim();
                if (tagContent === 'endfor') {
                    const closed = loopStack.pop();
                    if (closed) {
                        for (const name of closed.names) {
                            delete context[name];
                        }
                    }
                    continue;
                }

                const forMatch = tagContent.match(/^for\s+(.+?)\s+in\s+([a-zA-Z_][\w.]*)$/);
                if (!forMatch) {
                    continue;
                }

                const targetNames = forMatch[1]
                    .split(',')
                    .map(name => name.trim())
                    .filter(name => /^[a-zA-Z_]\w*$/.test(name));
                const iterPath = forMatch[2].split('.');
                const iterSchema = resolveSchemaPath(context, iterPath);
                const elementSchema = getCompletionChildren(iterSchema) || { __type__: 'Any' };

                for (const name of targetNames) {
                    context[name] = elementSchema;
                }
                context.loop = {
                    __type__: 'LoopObject',
                    index: { __type__: 'Integer' },
                    index0: { __type__: 'Integer' },
                    first: { __type__: 'Boolean' },
                    last: { __type__: 'Boolean' },
                    length: { __type__: 'Integer' }
                };
                loopStack.push({ names: targetNames });
            }
        }
    }


    // ==========================================
    // Language Server Providers Registration
    // ==========================================

    const completionProvider = vscode.languages.registerCompletionItemProvider(
        supportedLanguages,
        {
            provideCompletionItems(document, position) {
                const linePrefix = document.lineAt(position).text.substr(0, position.character);

                // Only provide completions inside Jinja delimiters
                if (!linePrefix.includes('{{') && !linePrefix.includes('{%')) return undefined;

                const completionItems: vscode.CompletionItem[] = [];

                // 1. Filter Completions (Triggered by '|')
                if (/\|\s*[a-zA-Z0-9_]*$/.test(linePrefix)) {
                    // Inject Custom Backend Filters
                    for (const [pyPath, filters] of filterRegistry.entries()) {
                        for (const filter of filters) {
                            const item = new vscode.CompletionItem(filter.name, vscode.CompletionItemKind.Function);
                            item.detail = `Custom Filter: ${filter.signature}`;
                            item.documentation = new vscode.MarkdownString(`**${filter.docstring || ''}**\n\nSource: \`${path.basename(pyPath)}\``);
                            if (filter.args && filter.args.length > 0) {
                                const snippetArgs = filter.args.map((arg: string, idx: number) => `\${${idx + 1}:${arg}}`).join(', ');
                                item.insertText = new vscode.SnippetString(`${filter.name}(${snippetArgs})`);
                            } else item.insertText = filter.name;
                            completionItems.push(item);
                        }
                    }
                    // Inject Built-in Filters
                    for (const [name, info] of Object.entries(BUILTIN_FILTERS)) {
                        const item = new vscode.CompletionItem(name, vscode.CompletionItemKind.Function);
                        item.detail = `Built-in: ${info.signature}`;
                        item.documentation = new vscode.MarkdownString(`${info.description}\n\n*💡 Caveat: ${info.caveat || 'None'}*`);
                        const argsMatch = info.signature.match(/\((.*)\)/);
                        if (argsMatch && argsMatch[1] && argsMatch[1] !== 'value' && argsMatch[1] !== 's' && argsMatch[1] !== 'seq' && argsMatch[1] !== 'obj') {
                            item.insertText = new vscode.SnippetString(`${name}($1)`);
                        } else item.insertText = name;
                        completionItems.push(item);
                    }
                    return completionItems;
                }

                // 2. Test Completions (Triggered by 'is ')
                if (/\s+is\s+[a-zA-Z0-9_]*$/.test(linePrefix)) {
                    for (const [name, info] of Object.entries(BUILTIN_TESTS)) {
                        const item = new vscode.CompletionItem(name, vscode.CompletionItemKind.TypeParameter);
                        item.detail = `Jinja Test: ${info.signature}`;
                        item.documentation = new vscode.MarkdownString(info.description);
                        completionItems.push(item);
                    }
                    return completionItems;
                }

                // 3. Tag Completions (Triggered by '{% ')
                const tagMatch = linePrefix.match(/\{%\s+([a-zA-Z0-9_]*)$/);
                if (tagMatch) {
                    const currentWord = tagMatch[1];
                    const lineText = document.lineAt(position.line).text;
                    const afterCursor = lineText.substring(position.character);

                    // Smart cursor positioning post-completion
                    let endPosition = position;
                    if (afterCursor.startsWith(' %}')) endPosition = position.translate(0, 3);
                    else if (afterCursor.startsWith('%}')) endPosition = position.translate(0, 2);
                    else if (afterCursor.startsWith('}')) endPosition = position.translate(0, 1);

                    for (const [name, info] of Object.entries(BUILTIN_TAGS)) {
                        const item = new vscode.CompletionItem(name, vscode.CompletionItemKind.Keyword);
                        item.detail = `Jinja Tag`;
                        item.documentation = new vscode.MarkdownString(`**Syntax**: \`${info.syntax}\`\n\n${info.description}\n\n*💡 Caveat: ${info.caveat}*`);
                        const startPos = position.translate(0, -currentWord.length);
                        item.range = new vscode.Range(startPos, endPosition);
                        item.insertText = new vscode.SnippetString(info.snippet);
                        completionItems.push(item);
                    }
                    return completionItems;
                }

                // 4. Parent Block Name Completions (Triggered inside '{% block ... %}')
                const blockNameMatch = linePrefix.match(/\{%-?\s*block\s+([a-zA-Z0-9_]*)$/);
                if (blockNameMatch) {
                    const currentWord = blockNameMatch[1];
                    const currentHtmlName = getTemplateKey(document.fileName);
                    const overridableBlocks = getOverridableBlocksForTemplate(currentHtmlName);
                    const startPos = position.translate(0, -currentWord.length);
                    const replaceRange = new vscode.Range(startPos, position);

                    for (const blockName of overridableBlocks) {
                        const item = new vscode.CompletionItem(blockName, vscode.CompletionItemKind.Property);
                        item.detail = 'Overridable Jinja block';
                        item.documentation = new vscode.MarkdownString(`Block inherited from a parent template and available to override.`);
                        item.insertText = blockName;
                        item.range = replaceRange;
                        completionItems.push(item);
                    }

                    return completionItems;
                }

                // 5. Variable and Property Completions
                const inJinjaContextMatch = linePrefix.match(/(?:\{\{|\{%)[^{}%]*$/);
                if (inJinjaContextMatch) {
                    const jinjaText = inJinjaContextMatch[0];

                    const mergedContext = buildStrictContext(document, position);

                    // Handle Nested Property Access (e.g., user.profile.)
                    const propMatch = jinjaText.match(/([a-zA-Z0-9_]+(?:\.[a-zA-Z0-9_]+)*)\.([a-zA-Z0-9_]*)$/);
                    if (propMatch) {
                        const basePath = propMatch[1];
                        const parts = basePath.split('.');
                        let currentLevel = mergedContext;

                        for (const part of parts) {
                            if (currentLevel && typeof currentLevel === 'object' && part in currentLevel) {
                                currentLevel = currentLevel[part];
                            } else {
                                currentLevel = undefined; break;
                            }
                        }

                        const completionLevel = getCompletionChildren(currentLevel);
                        if (completionLevel && typeof completionLevel === 'object') {
                            for (const [key, val] of Object.entries(completionLevel)) {
                                // Filter out internal metadata keys
                                if (['__type__', 'def_line', 'args', 'signature', '__is_iterable__', '__element__'].includes(key)) continue;

                                const isCallable = (val as any)?.__type__ === 'Function' || (val as any)?.__type__ === 'Macro';
                                const kind = isCallable ? vscode.CompletionItemKind.Method : vscode.CompletionItemKind.Property;
                                const item = new vscode.CompletionItem(key, kind);
                                item.detail = `OmniJinja: ${getDisplayType(val)}`;

                                // Auto-inject parenthesis for callable properties
                                if (isCallable) {
                                    const methodVal = val as any;
                                    if (methodVal.args && Array.isArray(methodVal.args)) {
                                        if (methodVal.args.length > 0) {
                                            const snippetArgs = methodVal.args.map((arg: string, index: number) => `\${${index + 1}:${arg}}`).join(', ');
                                            item.insertText = new vscode.SnippetString(`${key}(${snippetArgs})`);
                                        } else item.insertText = new vscode.SnippetString(`${key}()$0`);
                                    }
                                } else item.insertText = key;
                                completionItems.push(item);
                            }
                        }

                        return completionItems;
                    }

                    // Handle Base Variable Access (e.g., user)
                    const isDoubleBraceVar = linePrefix.match(/\{\{.*?([a-zA-Z0-9_]*)$/);
                    const isTagVar = linePrefix.match(/\{%\s+[a-zA-Z0-9_]+\s+.*?([a-zA-Z0-9_]*)$/);
                    const rootMatch = isDoubleBraceVar || isTagVar;

                    if (rootMatch) {
                        for (const [varName, varInfo] of Object.entries(mergedContext)) {
                            const isCallable = (varInfo as any)?.__type__ === 'Function' || (varInfo as any)?.__type__ === 'Macro';
                            const kind = isCallable ? vscode.CompletionItemKind.Function : vscode.CompletionItemKind.Variable;
                            const item = new vscode.CompletionItem(varName, kind);
                            item.detail = `OmniJinja: ${getDisplayType(varInfo)}`;

                            if (isCallable && (varInfo as any).args) {
                                const argsList = (varInfo as any).args as string[];
                                const snippetArgs = argsList.map((arg: string, index: number) => `\${${index + 1}:${arg}}`).join(', ');
                                item.insertText = new vscode.SnippetString(`${varName}(${snippetArgs})`);
                            }
                            completionItems.push(item);
                        }

                        // Inject Built-in Globals
                        for (const [name, info] of Object.entries(BUILTIN_GLOBALS)) {
                            const item = new vscode.CompletionItem(name, vscode.CompletionItemKind.Class);
                            item.detail = `Built-in Global: ${info.signature}`;
                            item.documentation = new vscode.MarkdownString(info.description);
                            if (info.snippet) item.insertText = new vscode.SnippetString(info.snippet);
                            else item.insertText = name;
                            completionItems.push(item);
                        }
                        return completionItems;
                    }
                    return undefined;
                }

                return undefined;
            }
        },
        ...COMPLETION_TRIGGER_CHARS
    );

    const templatePathProvider = vscode.languages.registerCompletionItemProvider(
        supportedLanguages,
        {
            provideCompletionItems(document, position) {
                const linePrefix = document.lineAt(position).text.substr(0, position.character);
                // Trigger only inside 'extends' or 'include' quotes
                const pathMatch = linePrefix.match(/\{%\s*(?:extends|include)\s+['"]([^'"]*)$/);
                if (pathMatch) {
                    const completionItems: vscode.CompletionItem[] = [];
                    const uniquePaths = new Set<string>();

                    for (const paths of templateFilesRegistry.values()) {
                        for (const p of paths) uniquePaths.add(p);
                    }

                    for (const templatePath of uniquePaths) {
                        const item = new vscode.CompletionItem(templatePath, vscode.CompletionItemKind.File);
                        item.detail = "Jinja Template";
                        item.insertText = templatePath;
                        completionItems.push(item);
                    }
                    return completionItems;
                }
                return undefined;
            }
        },
        '"', "'"
    );

    const hoverProvider = vscode.languages.registerHoverProvider(
        supportedLanguages,
        {
            provideHover(document, position) {
                const wordRange = document.getWordRangeAtPosition(position);
                if (!wordRange) return undefined;
                const hoveredWord = document.getText(wordRange);
                const lineText = document.lineAt(position.line).text;
                const textUpToHover = lineText.substring(0, wordRange.end.character);

                // Check standard built-ins first
                if (BUILTIN_TAGS[hoveredWord]) return createBuiltinHover('tag', BUILTIN_TAGS[hoveredWord].syntax, BUILTIN_TAGS[hoveredWord].description, BUILTIN_TAGS[hoveredWord].caveat);
                if (BUILTIN_FILTERS[hoveredWord]) return createBuiltinHover('filter', BUILTIN_FILTERS[hoveredWord].signature, BUILTIN_FILTERS[hoveredWord].description, BUILTIN_FILTERS[hoveredWord].caveat);
                if (BUILTIN_TESTS[hoveredWord]) return createBuiltinHover('test', BUILTIN_TESTS[hoveredWord].signature, BUILTIN_TESTS[hoveredWord].description);
                if (BUILTIN_GLOBALS[hoveredWord]) return createBuiltinHover('global', BUILTIN_GLOBALS[hoveredWord].signature, BUILTIN_GLOBALS[hoveredWord].description);

                // Check custom Python filters
                for (const [pyPath, filters] of filterRegistry.entries()) {
                    const foundFilter = filters.find((f: any) => f.name === hoveredWord);
                    if (foundFilter) {
                        const md = new vscode.MarkdownString();
                        md.appendCodeblock(`(filter) ${foundFilter.signature}`, 'python');
                        if (foundFilter.docstring) md.appendMarkdown(`\n---\n${foundFilter.docstring}`);
                        return new vscode.Hover(md);
                    }
                }

                const mergedContext = buildStrictContext(document, position);

                let foundValue: any = undefined;

                // Attempt precise path matching first (e.g., user.profile)
                const pathMatch = textUpToHover.match(/([a-zA-Z0-9_]+(?:\.[a-zA-Z0-9_]+)*)$/);
                if (pathMatch) {
                    const fullPath = pathMatch[1];
                    const parts = fullPath.split('.');
                    let currentLevel = mergedContext;
                    let validPath = true;
                    for (const part of parts) {
                        if (currentLevel && typeof currentLevel === 'object' && part in currentLevel) {
                            currentLevel = currentLevel[part];
                        } else {
                            validPath = false; break;
                        }
                    }
                    if (validPath) foundValue = currentLevel;
                }

                // Fallback to deep recursive search if exact path fails
                if (!foundValue) {
                    const deepSearch = (obj: any) => {
                        if (!obj || typeof obj !== 'object') return;
                        if (obj[hoveredWord]) { foundValue = obj[hoveredWord]; return; }
                        for (const key in obj) {
                            if (!['__type__', 'def_line', 'args', 'signature', '__is_iterable__'].includes(key) && typeof obj[key] === 'object') {
                                deepSearch(obj[key]);
                                if (foundValue) return;
                            }
                        }
                    };
                    deepSearch(mergedContext);
                }

                if (foundValue) {
                    const md = new vscode.MarkdownString();
                    const typeStr = getDisplayType(foundValue);

                    const isCallable = foundValue && typeof foundValue === 'object' && (foundValue.__type__ === 'Function' || foundValue.__type__ === 'Macro');
                    if (isCallable) {
                        const sig = foundValue.signature || `${hoveredWord}()`;
                        const label = foundValue.__type__ === 'Macro' ? 'macro' : 'method';
                        md.appendCodeblock(`(${label}) ${sig}`, 'python');
                        if (foundValue.docstring) md.appendMarkdown(`\n---\n${foundValue.docstring}`);
                    } else {
                        md.appendCodeblock(`(variable) ${hoveredWord}: ${typeStr}`, 'typescript');
                    }
                    return new vscode.Hover(md);
                }
                return undefined;
            }
        }
    );

    const signatureProvider = vscode.languages.registerSignatureHelpProvider(
        supportedLanguages,
        {
            provideSignatureHelp(document, position) {
                const linePrefix = document.lineAt(position).text.substring(0, position.character);

                // Process Custom Filters
                const filterMatch = linePrefix.match(/\|\s*([a-zA-Z0-9_]+)\s*\([^)]*$/);
                if (filterMatch) {
                    const funcName = filterMatch[1];
                    const argsString = filterMatch[0].substring(filterMatch[0].indexOf('(') + 1);
                    const activeParameterIndex = (argsString.match(/,/g) || []).length;

                    for (const filters of filterRegistry.values()) {
                        const filter = filters.find(f => f.name === funcName);
                        if (filter) {
                            const sigHelp = new vscode.SignatureHelp();
                            const sigInfo = new vscode.SignatureInformation(
                                filter.signature,
                                new vscode.MarkdownString(filter.docstring ? `**${filter.docstring}**` : '')
                            );
                            if (filter.args && Array.isArray(filter.args)) {
                                sigInfo.parameters = filter.args.map((argName: string) => new vscode.ParameterInformation(argName));
                            }
                            sigHelp.signatures = [sigInfo];
                            sigHelp.activeSignature = 0;
                            sigHelp.activeParameter = activeParameterIndex;
                            return sigHelp;
                        }
                    }
                }

                // Process Methods and Macros
                const methodMatch = linePrefix.match(/([a-zA-Z0-9_]+(?:\.[a-zA-Z0-9_]+)*)\s*\([^)]*$/);
                if (methodMatch) {
                    const fullPath = methodMatch[1];
                    const parts = fullPath.split('.');

                    const mergedContext = buildStrictContext(document, position);

                    let currentLevel = mergedContext;
                    for (const part of parts) {
                        if (currentLevel && typeof currentLevel === 'object' && part in currentLevel) {
                            currentLevel = currentLevel[part];
                        } else {
                            currentLevel = undefined; break;
                        }
                    }

                    const isCallable = currentLevel && (currentLevel.__type__ === 'Function' || currentLevel.__type__ === 'Macro');
                    if (isCallable) {
                        const sigHelp = new vscode.SignatureHelp();
                        const sigInfo = new vscode.SignatureInformation(
                            currentLevel.signature || `${parts[parts.length-1]}()`,
                            new vscode.MarkdownString(currentLevel.docstring ? `**${currentLevel.docstring}**` : '')
                        );
                        if (currentLevel.args && Array.isArray(currentLevel.args)) {
                            sigInfo.parameters = currentLevel.args.map((argName: string) => new vscode.ParameterInformation(argName));
                        }

                        const argsString = methodMatch[0].substring(methodMatch[0].indexOf('(') + 1);
                        const activeParameterIndex = (argsString.match(/,/g) || []).length;

                        sigHelp.signatures = [sigInfo];
                        sigHelp.activeSignature = 0;
                        sigHelp.activeParameter = activeParameterIndex;
                        return sigHelp;
                    }
                }
                return undefined;
            }
        },
        '(', ','
    );

    const definitionProvider = vscode.languages.registerDefinitionProvider(
        supportedLanguages,
        {
            provideDefinition(document, position) {
                const wordRange = document.getWordRangeAtPosition(position);
                if (!wordRange) return undefined;
                const word = document.getText(wordRange);

                // Look up definitions for Custom Filters
                for (const [pyPath, filters] of filterRegistry.entries()) {
                    const targetFilter = filters.find(f => f.name === word);
                    if (targetFilter) {
                        const lineNum = targetFilter.line ? targetFilter.line - 1 : 0;
                        return new vscode.Location(vscode.Uri.file(pyPath), new vscode.Position(lineNum, 0));
                    }
                }

                // Look up definitions for Context Variables
                const currentHtmlName = getTemplateKey(document.fileName);
                const pySourcesMap = templateRegistry.get(currentHtmlName);
                if (pySourcesMap) {
                    for (const [pyPath, contextData] of pySourcesMap.entries()) {
                        let found = false;
                        let targetLine = 0;

                        const pathMatch = document.lineAt(position.line).text.substring(0, wordRange.end.character).match(/([a-zA-Z0-9_]+(?:\.[a-zA-Z0-9_]+)*)$/);
                        if (pathMatch) {
                            const fullPath = pathMatch[1];
                            const parts = fullPath.split('.');
                            let currentLevel = contextData;
                            let validPath = true;
                            for (const part of parts) {
                                if (currentLevel && typeof currentLevel === 'object' && part in currentLevel) {
                                    currentLevel = currentLevel[part];
                                } else {
                                    validPath = false; break;
                                }
                            }
                            if (validPath) {
                                found = true;
                                if (currentLevel) targetLine = (currentLevel.def_line || 1) - 1;
                            }
                        }

                        if (!found) {
                            const deepSearch = (obj: any) => {
                                if (!obj || typeof obj !== 'object') return;
                                if (word in obj) {
                                    found = true;
                                    const targetObj = obj[word];
                                    if (targetObj && typeof targetObj === 'object') {
                                        const rawLine = targetObj.def_line || targetObj.line;
                                        if (rawLine) targetLine = rawLine - 1;
                                    }
                                    return;
                                }
                                for (const key in obj) {
                                    if (!['__type__', 'def_line', 'args', 'signature', '__is_iterable__'].includes(key) && typeof obj[key] === 'object') {
                                        deepSearch(obj[key]);
                                        if (found) return;
                                    }
                                }
                            };
                            deepSearch(contextData);
                        }
                        if (found) return new vscode.Location(vscode.Uri.file(pyPath), new vscode.Position(targetLine, 0));
                    }
                }
                return undefined;
            }
        }
    );

    context.subscriptions.push(
        pyChangeListener,
        htmlChangeListener,
        watcher,
        htmlWatcher,
        completionProvider,
        hoverProvider,
        signatureProvider,
        definitionProvider,
        templatePathProvider
    );
    // Register the command to handle the "Ignore" action
    context.subscriptions.push(vscode.commands.registerCommand('omnijinja.ignoreDiagnostic', (uri: vscode.Uri, diagnostic: vscode.Diagnostic) => {
        const key = getDiagnosticKey(uri, diagnostic.range.start.line, diagnostic.message);

        // Add the diagnostic identifier to our local blacklist
        ignoredDiagnosticsCache.add(key);

        // Immediately refresh the UI by filtering out the ignored diagnostic
        const currentDiagnostics = diagnosticCollection.get(uri) || [];
        const filtered = currentDiagnostics.filter(d =>
            getDiagnosticKey(uri, d.range.start.line, d.message) !== key
        );

        diagnosticCollection.set(uri, filtered);

        // Optional: Notify the user that the ignore is temporary for this session
        vscode.window.setStatusBarMessage("Warning ignored for this session.", 3000);
    }));
}

// ==========================================
// Subprocess Execution & Data Loading
// ==========================================

/**
 * Triggers the Python parsing script asynchronously for queued .py files.
 */
async function processQueue(enginePath: string, workspaceRoot: string, storagePath: string) {
    if (isParsing || parseQueue.length === 0) {
        return;
    }
    isParsing = true;

    while (parseQueue.length > 0) {
        const filePath = parseQueue.shift()!;
        const scriptPath = path.join(enginePath, 'main_py_parser.py');
        const command = `${activePythonCmd} "${scriptPath}" "${filePath}" "${workspaceRoot}" "${storagePath}"`;

        const doc = vscode.workspace.textDocuments.find(d => d.uri.fsPath === filePath);
        const content = doc ? doc.getText() : fs.readFileSync(filePath, 'utf-8');

        try {
            await new Promise((resolve, reject) => {
                const child = exec(command, (error, stdout) => {
                    if (error) reject(error);
                    else resolve(stdout);
                });
                if (child.stdin) {
                    child.stdin.write(content);
                    child.stdin.end();
                }
            });
            loadSchemaIntoMemory(filePath, workspaceRoot, storagePath, enginePath);
        } catch (e) {
            console.error(`Python Backend Parsing Error: ${filePath}`, e);
        }
    }
    isParsing = false;
}

/**
 * Triggers the Jinja syntax detection script asynchronously for queued templates.
 */
async function processJinjaQueue(enginePath: string, workspaceRoot: string, storagePath: string) {
    if (isJinjaParsing || jinjaParseQueue.length === 0) {
        return;
    }
    isJinjaParsing = true;

    try {
        while (jinjaParseQueue.length > 0) {
            const filePath = jinjaParseQueue.shift()!;
            const scriptPath = path.join(enginePath, 'main_jinja_parser.py');
            const command = `${activePythonCmd} "${scriptPath}" "${filePath}" "${workspaceRoot}" "${storagePath}"`;
            const doc = vscode.workspace.textDocuments.find(d => d.uri.fsPath === filePath);
            const content = doc ? doc.getText() : fs.readFileSync(filePath, 'utf-8');

            try {
                await new Promise((resolve, reject) => {
                    const child = exec(command, (error, stdout) => {
                        if (error) reject(error);
                        else resolve(stdout);
                    });
                    if (child.stdin) {
                        child.stdin.write(content);
                        child.stdin.end();
                    }
                });
                loadJinjaSchemaIntoMemory(filePath, workspaceRoot, storagePath);
            } catch (e) {
                console.error(`Jinja Syntax Parsing Error: ${filePath}`, e);
            }
        }
    } finally {
        isJinjaParsing = false;
    }

    if (jinjaParseQueue.length > 0) {
        processJinjaQueue(enginePath, workspaceRoot, storagePath);
    }
}

/**
 * Reads the generated _schema.json file and updates the in-memory registries.
 */
function loadSchemaIntoMemory(pyFilePath: string, workspaceRoot: string, storagePath: string, enginePath: string) {    const safeName = getSafePyName(pyFilePath, workspaceRoot);
    const jsonPath = path.join(storagePath, 'backend_schemas', safeName);

    if (!fs.existsSync(jsonPath)) return;

    try {
        const schemaData = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));

        const affectedTemplates = new Set<string>();

        const oldCalls = renderCallRegistry.get(pyFilePath);
        if (oldCalls) {
            for (const oldCall of oldCalls) {
                const oldTemplateName = oldCall.template.replace(/\\/g, '/');
                affectedTemplates.add(oldTemplateName);

                const sourceMap = templateRegistry.get(oldTemplateName);
                if (sourceMap && sourceMap.has(pyFilePath)) {
                    sourceMap.delete(pyFilePath);
                    if (sourceMap.size === 0) templateRegistry.delete(oldTemplateName);
                }
            }
        }

        if (schemaData.render_calls) {
            renderCallRegistry.set(pyFilePath, schemaData.render_calls);

            for (const call of schemaData.render_calls) {
                const templateName = call.template.replace(/\\/g, '/');
                affectedTemplates.add(templateName);

                if (!templateRegistry.has(templateName)) {
                    templateRegistry.set(templateName, new Map<string, any>());
                }
                templateRegistry.get(templateName)!.set(pyFilePath, call.context);
            }

            validateDataFlow(pyFilePath);
        } else {
            renderCallRegistry.delete(pyFilePath);
            pyDiagnosticCollection.delete(vscode.Uri.file(pyFilePath));
        }

        for (const templateName of affectedTemplates) {
            vscode.workspace.findFiles(`**/${templateName}`, '**/{node_modules,.venv,venv}/**').then(uris => {
                if (uris.length > 0) {
                    const htmlPath = uris[0].fsPath;

                    if (!jinjaParseQueue.includes(htmlPath)) {
                        jinjaParseQueue.push(htmlPath);
                    }
                    processJinjaQueue(enginePath, workspaceRoot, storagePath);
                }
            });
        }

        if (schemaData.custom_filters && schemaData.custom_filters.length > 0) {
            filterRegistry.set(pyFilePath, schemaData.custom_filters);
        } else {
            filterRegistry.delete(pyFilePath);
        }

        if (schemaData.template_files && Array.isArray(schemaData.template_files) && schemaData.template_files.length > 0) {
            templateFilesRegistry.set(pyFilePath, new Set(schemaData.template_files));
        } else {
            templateFilesRegistry.delete(pyFilePath);
        }

    } catch (e) {
        console.error("Failed to load backend JSON schema", e);
    }
}

/**
 * Reads the generated _jinja.json file from disk, updates internal registries,
 * and applies diagnostic wavy lines to the editor while respecting the ignore blacklist.
 * * @param htmlFilePath - The absolute path to the template file (HTML/Jinja).
 * @param workspaceRoot - The root path of the current workspace.
 */
function loadJinjaSchemaIntoMemory(htmlFilePath: string, workspaceRoot: string, storagePath: string) {

    const templateKey = getTemplateKey(htmlFilePath);
    const safeName = getSafeJinjaName(htmlFilePath, workspaceRoot);
    const jsonPath = path.join(storagePath, 'jinja_schemas', safeName);

    const uri = vscode.Uri.file(htmlFilePath);
    diagnosticCollection.delete(uri);

    // 1. Check if diagnostics are globally enabled in settings
    const config = vscode.workspace.getConfiguration('omnijinja');
    const enabled = config.get<boolean>('enableDiagnostics', true);

    // If schema file doesn't exist or diagnostics are disabled, clear existing markers and exit
    if (!fs.existsSync(jsonPath) || !enabled) {
        return;
    }

    try {
        const data = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));

        // 2. Update memory registries for internal variables and macros
        const internalData: any = {};
        if (data.internal_variables) {
            Object.assign(internalData, data.internal_variables);

            if (data.internal_variables.dependencies) {
                templateDependenciesRegistry.set(templateKey, data.internal_variables.dependencies);
            } else {
                templateDependenciesRegistry.delete(templateKey);
            }
        } else {
            templateDependenciesRegistry.delete(templateKey);
        }

        if (data.macros) {
            Object.assign(internalData, data.macros);
        }
        internalJinjaRegistry.set(templateKey, internalData);

        if (Array.isArray(data.blocks)) {
            templateBlocksRegistry.set(templateKey, data.blocks);
        } else {
            templateBlocksRegistry.delete(templateKey);
        }

        // 3. Cache the repaired code for the Quick Fix (Lightbulb) feature
        if (data.fixed_code) {
            fixedCodeRegistry.set(htmlFilePath, data.fixed_code);
        } else {
            fixedCodeRegistry.delete(htmlFilePath);
        }

        // 4. Update External Requirements (Demand) and trigger cross-file validation
        if (data.external_requirements) {
            externalRequirementsRegistry.set(templateKey, data.external_requirements);

            // Re-validate all Python files that supply variables to this specific template
            const pySourcesMap = templateRegistry.get(templateKey);
            if (pySourcesMap) {
                for (const pyPath of pySourcesMap.keys()) {
                    validateDataFlow(pyPath);
                }
            }
        } else {
            externalRequirementsRegistry.delete(templateKey);
        }

        // 5. Process and render Diagnostics (Wavy Underlines)
        if (data.diagnostics && Array.isArray(data.diagnostics)) {
            const diagnostics: vscode.Diagnostic[] = [];

            // Check if this template is currently linked to any Python backend logic
            const isLinked = templateRegistry.has(templateKey) && templateRegistry.get(templateKey)!.size > 0;

            for (const diag of data.diagnostics) {
                const lineNum = Math.max(0, (diag.line || 1) - 1);
                const message = diag.message;

                // --- SILENT IGNORE FILTER ---
                // Skip this diagnostic if its unique key exists in the local ignore cache
                if (ignoredDiagnosticsCache.has(getDiagnosticKey(uri, lineNum, message))) {
                    continue;
                }

                // --- CONTEXTUAL FILTER ---
                // Suppress "Undefined" warnings if the template isn't linked to a backend yet
                const isUndefinedWarning = message.toLowerCase().includes('undefined');
                if (!isLinked && isUndefinedWarning) {
                    continue;
                }

                if (diagnosticIsSatisfiedByEffectiveContext(message, templateKey)) {
                    continue;
                }

                // --- RANGE CALCULATION ---
                let colNum = 0;
                let length = 1000; // Default to a long length if column data is missing

                if (diag.col) {
                    colNum = Math.max(0, diag.col - 1);
                    length = diag.original ? String(diag.original).length : 5;
                }

                const range = new vscode.Range(lineNum, colNum, lineNum, colNum + length);
                const severity = diag.severity === 'error' ?
                    vscode.DiagnosticSeverity.Error :
                    vscode.DiagnosticSeverity.Warning;

                // Create the VS Code diagnostic object
                const diagnostic = new vscode.Diagnostic(range, message, severity);
                diagnostic.source = 'OmniJinja';
                diagnostics.push(diagnostic);
            }

            if (diagnostics.length > 0) {
                diagnosticCollection.set(uri, diagnostics);
            }
        } else {
            return;
        }

    } catch (e) {
        console.error(`OmniJinja: Failed to load Jinja JSON schema for ${templateKey}`, e);
    }
}


// ==========================================
// Cross-File Data Flow Validation Engine
// ==========================================

/**
 * Validates a specific Python file by comparing its provided context (Supply)
 * against the external requirements (Demand) of the HTML templates it renders.
 */
function validateDataFlow(pyFilePath: string) {
    const calls = renderCallRegistry.get(pyFilePath);
    if (!calls) {
        return;
    }

    const diagnostics: vscode.Diagnostic[] = [];

    for (const call of calls) {
        const templateName = call.template.replace(/\\/g, '/');
        const demand = buildEffectiveExternalRequirements(templateName);

        if (!demand || Object.keys(demand).length === 0) {
            continue;
        }

        const supply = call.context || {};
        const lineNum = Math.max(0, (call.render_line || 1) - 1);

        for (const [reqKey, reqVal] of Object.entries(demand)) {
            if (reqKey.startsWith('__')) {
                continue;
            }

            if (!(reqKey in supply)) {
                // ROOT MISSING -> Warning
                const range = new vscode.Range(lineNum, 0, lineNum, 50); // Highlight start of line
                diagnostics.push(new vscode.Diagnostic(
                    range,
                    `OmniJinja [DataFlow]: Template '${templateName}' requires variable '${reqKey}' which is not provided in render_template.`,
                    vscode.DiagnosticSeverity.Warning
                ));
            } else {
                // INITIATE DEEP CHECK
                checkDeep(reqKey, reqVal, supply[reqKey], templateName, lineNum, diagnostics);
            }
        }
    }

    // Publish diagnostics to the Python file
    pyDiagnosticCollection.set(vscode.Uri.file(pyFilePath), diagnostics);
}

/**
 * Recursively checks properties, callables, and iterables.
 */
function checkDeep(pathStr: string, demandNode: any, supplyNode: any, templateName: string, lineNum: number, diagnostics: vscode.Diagnostic[]) {
    if (!demandNode || typeof demandNode !== 'object') {
        return;
    }
    if (isGenericSchemaLeaf(supplyNode)) {
        return;
    }

    // 1. Behavior Check: Callable Mismatch -> Error
    if (demandNode.__is_callable__) {
        const sType = supplyNode?.__type__;
        if (sType && sType !== 'Function' && sType !== 'Method' && sType !== 'Macro' && sType !== 'Any') {
            const range = new vscode.Range(lineNum, 0, lineNum, 50);
            diagnostics.push(new vscode.Diagnostic(
                range,
                `OmniJinja [DataFlow]: '${pathStr}' is called as a function in '${templateName}', but Python provides type '${sType}'.`,
                vscode.DiagnosticSeverity.Warning
            ));
        }
    }

    // 2. Behavior Check: Iterable Mismatch -> Error
    if (demandNode.__is_iterable__) {
        const sType = supplyNode?.__type__;
        const isIterable = supplyNode?.__is_iterable__;
        if (sType && !isIterable && sType !== 'Iterable' && sType !== 'List' && sType !== 'Tuple' && sType !== 'Dict' && sType !== 'Any') {
            const range = new vscode.Range(lineNum, 0, lineNum, 50);
            diagnostics.push(new vscode.Diagnostic(
                range,
                `OmniJinja [DataFlow]: '${pathStr}' is iterated over in '${templateName}', but Python provides type '${sType}'.`,
                vscode.DiagnosticSeverity.Warning
            ));
        }
    }

    // 3. Deep Property Check -> Warning (Because Python dynamic nature might hide properties)
    for (const [key, val] of Object.entries(demandNode)) {
        if (key.startsWith('__')) {
            continue;
        }

        const childSupply = getSchemaChild(supplyNode, key);
        if (childSupply === undefined) {
            const range = new vscode.Range(lineNum, 0, lineNum, 50);
            diagnostics.push(new vscode.Diagnostic(
                range,
                `OmniJinja [DataFlow]: Template '${templateName}' expects property '${pathStr}.${key}', which might be missing in the provided context.`,
                vscode.DiagnosticSeverity.Warning
            ));
        } else {
            checkDeep(`${pathStr}.${key}`, val, childSupply, templateName, lineNum, diagnostics);
        }
    }
}

export function deactivate() {}
