/**
 * OmniJinja VS Code Extension 
 *
 * This module orchestrates the frontend language server features for Jinja2 templates.
 * It acts as the bridge between VS Code's Extension API and the Python-based OmniJinja 
 * analysis engine. Features include intelligent auto-completion, hover documentation, 
 * go-to-definition, real-time diagnostics (linting), and automated Quick Fixes.
 */

import * as vscode from 'vscode';
import { exec, execSync } from 'child_process';
import * as path from 'path';
import * as fs from 'fs';

// Import built-in Jinja2 definitions (tags, filters, tests, globals)
import { BUILTIN_FILTERS, BUILTIN_TAGS, BUILTIN_TESTS, BUILTIN_GLOBALS } from './jinja_builtins';

// ==========================================
// Memory Registries (State Management)
// ==========================================

/** * Caches context data passed from Python views to templates.
 * Map structure: Template Name -> Map<Python Source Path, Context Variables> 
 */
const templateRegistry = new Map<string, Map<string, any>>(); 

/** * Caches custom Flask filters extracted from Python code.
 * Map structure: Python Source Path -> Array of Filter Metadata 
 */
const filterRegistry = new Map<string, any[]>(); 

/** * Caches template files referenced within Python files.
 * Map structure: Python Source Path -> Set of Template Paths 
 */
const templateFilesRegistry = new Map<string, Set<string>>(); 

/** * Caches local variables defined within the Jinja template itself (e.g., via {% set %}).
 * Map structure: Template Name -> Local Context Variables 
 */
const internalJinjaRegistry = new Map<string, any>(); 

/** * Caches external requirements (Demand) parsed from Jinja templates.
 * Map structure: Template Name -> Requirements JSON Object
 */
const externalRequirementsRegistry = new Map<string, any>(); 

/** * Caches raw render calls (Supply) from Python files specifically for validation.
 * Map structure: Python Source Path -> Array of Render Calls
 */
const renderCallRegistry = new Map<string, any[]>();

/** Collection to render squiggly lines inside Python files */
let pyDiagnosticCollection: vscode.DiagnosticCollection;

/** * Caches the fully repaired source code generated by the Python fixer engine.
 * Map structure: HTML File Path -> Repaired Source Code String
 */
const fixedCodeRegistry = new Map<string, string>();

// Background task queues and debounce timers for performance optimization
const debounceTimers = new Map<string, NodeJS.Timeout>();
const parseQueue: string[] = [];
let isParsing = false;
const jinjaParseQueue: string[] = [];
let isJinjaParsing = false;

/** Collection to manage and render wavy underlines for syntax errors and warnings */
let diagnosticCollection: vscode.DiagnosticCollection;

/**
 * Formats a variable's internal schema into a human-readable type string for the UI.
 * * @param val - The variable schema object extracted by the Python backend.
 * @returns A formatted type string (e.g., "Iterable[Order]" or "String").
 */
function getDisplayType(val: any): string {
    if (typeof val === 'string') return val;
    if (Array.isArray(val)) {
        if (val.length > 0 && val[0] && val[0].__type__) return `Iterable[${val[0].__type__}]`;
        return 'Iterable';
    }
    if (val && typeof val === 'object') {
        if (val.__is_iterable__) {
            if (val.__element__) return `${val.__type__}[${val.__element__.__type__ || 'Object'}]`;
            return `${val.__type__}[...]`; 
        }
        return val.__type__ || 'Object'; 
    }
    return 'Unknown';
}

/**
 * Creates a formatted Markdown hover tooltip for built-in Jinja constructs.
 * * @param type - The construct category (e.g., 'tag', 'filter', 'test').
 * @param signature - The structural signature of the construct.
 * @param desc - Detailed explanation of what the construct does.
 * @param caveat - Optional edge-case warnings or important notes.
 * @returns A complete vscode.Hover object ready for rendering.
 */
function createBuiltinHover(type: string, signature: string, desc: string, caveat?: string): vscode.Hover {
    const md = new vscode.MarkdownString();
    md.appendCodeblock(`(${type}) Usage: ${signature}`, 'python');
    md.appendMarkdown(`\n---\n${desc}`);
    if (caveat) md.appendMarkdown(`\n\n*💡 **Caveat**: ${caveat}*`);
    return new vscode.Hover(md);
}

// ==========================================
// Code Action Provider (Lightbulb Quick Fix)
// ==========================================

/**
 * Provides automated Quick Fix actions for detected Jinja syntax errors.
 * It retrieves the pre-calculated repaired code from the `fixedCodeRegistry`.
 */
export class OmniJinjaFixer implements vscode.CodeActionProvider {
    public provideCodeActions(
        document: vscode.TextDocument, 
        range: vscode.Range | vscode.Selection, 
        context: vscode.CodeActionContext, 
        token: vscode.CancellationToken
    ): vscode.ProviderResult<(vscode.CodeAction | vscode.Command)[]> {
        
        // Step 1: Verify if an 'Error' level diagnostic from OmniJinja exists at the cursor
        const hasSyntaxError = context.diagnostics.some(
            d => d.severity === vscode.DiagnosticSeverity.Error && d.source === 'OmniJinja'
        );
        
        if (!hasSyntaxError) {
            return [];
        }

        // Step 2: Retrieve the repaired code provided by the Python backend (fixer.py)
        const fixedCode = fixedCodeRegistry.get(document.uri.fsPath);
        if (!fixedCode) {
            return [];
        }

        // Step 3: Construct the Quick Fix action (Lightbulb 💡)
        const fixAction = new vscode.CodeAction('Fix Jinja Syntax Error (OmniJinja Auto-Fix)', vscode.CodeActionKind.QuickFix);
        fixAction.edit = new vscode.WorkspaceEdit();

        // Step 4: Define the replacement range to cover the entire document
        const fullRange = new vscode.Range(
            document.positionAt(0),
            document.positionAt(document.getText().length)
        );

        fixAction.edit.replace(document.uri, fullRange, fixedCode);
        fixAction.isPreferred = true; // Instructs VS Code to prioritize this fix

        return [fixAction];
    }
}

// ==========================================
// Extension Activation & Lifecycle
// ==========================================

let activePythonCmd = 'python'; 

async function resolvePythonPath(): Promise<string | undefined> {
    const config = vscode.workspace.getConfiguration('omnijinja');
    const customPath = config.get<string>('pythonPath');
    if (customPath && customPath.trim() !== '') return customPath;

    const commands = ['python3', 'python'];
    for (const cmd of commands) {
        try {
            execSync(`${cmd} --version`, { stdio: 'ignore', timeout: 1000 });
            return cmd;
        } catch (e) {
            continue;
        }
    }
    return undefined; 
}


export async function activate(context: vscode.ExtensionContext) {
    console.log('🚀 OmniJinja activated successfully!');

    const resolvedCmd = await resolvePythonPath();
    if (!resolvedCmd) {
        vscode.window.showErrorMessage(
            "OmniJinja: Unable to find Python environment (python or python3). Please ensure that Python is installed, or manually specify the path in settings.",
            "Open Settings"
        ).then(selection => {
            if (selection === "Open Settings") {
                vscode.commands.executeCommand('workbench.action.openSettings', 'omnijinja.pythonPath');
            }
        });
        return; 
    }
    activePythonCmd = resolvedCmd; // 保存探测到的可用命令

    diagnosticCollection = vscode.languages.createDiagnosticCollection('omnijinja');
    context.subscriptions.push(diagnosticCollection);

    // Initialize Python diagnostics
    pyDiagnosticCollection = vscode.languages.createDiagnosticCollection('omnijinja-python');
    context.subscriptions.push(pyDiagnosticCollection);

    const workspaceRoot = vscode.workspace.workspaceFolders?.[0].uri.fsPath;
    if (!workspaceRoot) return;
    const pythonEnginePath = path.join(context.extensionPath, 'python_engine');

    const supportedLanguages = ['html', 'jinja', 'django-html', 'jinja-html', 'django-txt'];

    // Register the Quick Fix Code Action Provider
    context.subscriptions.push(
        vscode.languages.registerCodeActionsProvider(
            supportedLanguages, 
            new OmniJinjaFixer(), 
            { providedCodeActionKinds: [vscode.CodeActionKind.QuickFix] }
        )
    );

    // Initial workspace scan: Find and queue all relevant Python files and Jinja templates
    vscode.window.withProgress({
        location: vscode.ProgressLocation.Window,
        title: "OmniJinja: Initializing Workspace...",
    }, async (progress) => {
        // Process Python files
        const pyFiles = await vscode.workspace.findFiles('**/*.py', '**/{node_modules,.venv,venv}/**');
        const filesToParse = pyFiles.filter(uri => {
            const content = fs.readFileSync(uri.fsPath, 'utf-8');
            // Optimization: Only parse files likely to contain Flask/Jinja logic
            return content.includes('flask') || content.includes('jinja');
        });
        for (const file of filesToParse) parseQueue.push(file.fsPath);
        await processQueue(pythonEnginePath, workspaceRoot);

        // Process Jinja template files (html, jinja, j2, and other template extensions)
        const templatePatterns = ['**/*.html', '**/*.jinja', '**/*.j2', '**/*.jinja2'];
        const excludePattern = '**/{node_modules,.venv,venv}/**';
        
        for (const pattern of templatePatterns) {
            const templateFiles = await vscode.workspace.findFiles(pattern, excludePattern);
            for (const file of templateFiles) {
                if (!jinjaParseQueue.includes(file.fsPath)) {
                    jinjaParseQueue.push(file.fsPath);
                }
            }
        }
        await processJinjaQueue(pythonEnginePath, workspaceRoot);
    });

    // Real-time File Change Listeners for Instant Reprocessing
    const pyChangeListener = vscode.workspace.onDidChangeTextDocument((event) => {
        const document = event.document;
        if (document.languageId === 'python') {
            const filePath = document.uri.fsPath;
            if (debounceTimers.has(filePath)) clearTimeout(debounceTimers.get(filePath)!);
            debounceTimers.set(filePath, setTimeout(() => {
                if (!parseQueue.includes(filePath)) {
                    parseQueue.push(filePath);
                    processQueue(pythonEnginePath, workspaceRoot);
                }
                debounceTimers.delete(filePath);
            }, 300));
        }
    });

    const htmlChangeListener = vscode.workspace.onDidChangeTextDocument((event) => {
        const document = event.document;
        const validLangs = ['html', 'jinja', 'django-html', 'jinja-html'];
        if (validLangs.includes(document.languageId) || document.fileName.endsWith('.html')) {
            const filePath = document.uri.fsPath;
            if (debounceTimers.has(filePath)) clearTimeout(debounceTimers.get(filePath)!);
            debounceTimers.set(filePath, setTimeout(() => {
                if (!jinjaParseQueue.includes(filePath)) {
                    jinjaParseQueue.push(filePath);
                    processJinjaQueue(pythonEnginePath, workspaceRoot);
                }
                debounceTimers.delete(filePath);
            }, 300));
        }
    });

    // File Deletion Watchers to Clean Up Memory
    const watcher = vscode.workspace.createFileSystemWatcher('**/*.py');
    watcher.onDidDelete((uri) => {
        const deletedPyPath = uri.fsPath;
        const safeName = path.basename(deletedPyPath) + "_schema.json";
        const jsonPath = path.join(workspaceRoot, 'output_schemas', safeName);
        if (fs.existsSync(jsonPath)) fs.unlinkSync(jsonPath);

        for (const [templateName, sourceMap] of templateRegistry.entries()) {
            if (sourceMap.has(deletedPyPath)) {
                sourceMap.delete(deletedPyPath);
                if (sourceMap.size === 0) templateRegistry.delete(templateName);
            }
        }
        if (filterRegistry.has(deletedPyPath)) filterRegistry.delete(deletedPyPath);
        if (templateFilesRegistry.has(deletedPyPath)) templateFilesRegistry.delete(deletedPyPath);
    });

    const htmlWatcher = vscode.workspace.createFileSystemWatcher('**/*.{html,jinja,j2,jinja2}');
    
    htmlWatcher.onDidDelete((uri) => {
        const deletedHtmlPath = uri.fsPath;
        const baseName = path.basename(deletedHtmlPath);

        diagnosticCollection.delete(uri); 
        internalJinjaRegistry.delete(baseName);
        fixedCodeRegistry.delete(deletedHtmlPath);
        externalRequirementsRegistry.delete(baseName); 

        const safeName = baseName + "_jinja.json";
        const jsonPath = path.join(workspaceRoot, 'jinja_schemas', safeName);
        if (fs.existsSync(jsonPath)) {
            fs.unlinkSync(jsonPath);
        }
    });

    // ==========================================
    // Unified Context Builder
    // ==========================================

    function buildStrictContext(document: vscode.TextDocument, position: vscode.Position) {
        const currentHtmlName = path.basename(document.fileName);
        const mergedContext: any = {};
        
        // 1. Python Global Variables (Always visible)
        const pySourcesMap = templateRegistry.get(currentHtmlName);
        if (pySourcesMap) {
            for (const ctx of pySourcesMap.values()) Object.assign(mergedContext, ctx); 
        }
        
        // 2. Strict Spatial & Line Filtering
        const internalCtx = internalJinjaRegistry.get(currentHtmlName);
        if (internalCtx) {
            const activeLine = position.line + 1; // Translate to 1-based indexing

            // A. Globals (e.g., {% set %}) -> Must be defined BEFORE active line
            if (internalCtx.globals) {
                for (const [varName, varInfo] of Object.entries(internalCtx.globals)) {
                    const defLine = (varInfo as any).def_line || 0;
                    if (activeLine >= defLine) {
                        mergedContext[varName] = varInfo;
                    }
                }
            }
            
            // B. Scoped (e.g., {% for %}) -> Must be WITHIN start and end bounds
            if (internalCtx.scoped) {
                for (const scope of internalCtx.scoped) {
                    if (activeLine >= scope.scope_range.start_line && activeLine <= scope.scope_range.end_line) {
                        Object.assign(mergedContext, scope.vars);
                    }
                }
            }
            
            // C. Macros (Hoisted, always visible)
            for (const key in internalCtx) {
                if (key !== 'globals' && key !== 'scoped') {
                    mergedContext[key] = internalCtx[key];
                }
            }
        }
        return mergedContext;
    }

    // ==========================================
    // Language Server Providers Registration
    // ==========================================

    const completionProvider = vscode.languages.registerCompletionItemProvider(
        supportedLanguages,
        {
            provideCompletionItems(document, position) {
                const linePrefix = document.lineAt(position).text.substr(0, position.character);
                
                // Only provide completions inside Jinja delimiters
                if (!linePrefix.includes('{{') && !linePrefix.includes('{%')) return undefined;

                const completionItems: vscode.CompletionItem[] = [];

                // 1. Filter Completions (Triggered by '|')
                if (/\|\s*[a-zA-Z0-9_]*$/.test(linePrefix)) {
                    // Inject Custom Backend Filters
                    for (const [pyPath, filters] of filterRegistry.entries()) {
                        for (const filter of filters) {
                            const item = new vscode.CompletionItem(filter.name, vscode.CompletionItemKind.Function);
                            item.detail = `Custom Filter: ${filter.signature}`;
                            item.documentation = new vscode.MarkdownString(`**${filter.docstring || ''}**\n\nSource: \`${path.basename(pyPath)}\``);
                            if (filter.args && filter.args.length > 0) {
                                const snippetArgs = filter.args.map((arg: string, idx: number) => `\${${idx + 1}:${arg}}`).join(', ');
                                item.insertText = new vscode.SnippetString(`${filter.name}(${snippetArgs})`);
                            } else item.insertText = filter.name;
                            completionItems.push(item);
                        }
                    }
                    // Inject Built-in Filters
                    for (const [name, info] of Object.entries(BUILTIN_FILTERS)) {
                        const item = new vscode.CompletionItem(name, vscode.CompletionItemKind.Function);
                        item.detail = `Built-in: ${info.signature}`;
                        item.documentation = new vscode.MarkdownString(`${info.description}\n\n*💡 Caveat: ${info.caveat || 'None'}*`);
                        const argsMatch = info.signature.match(/\((.*)\)/);
                        if (argsMatch && argsMatch[1] && argsMatch[1] !== 'value' && argsMatch[1] !== 's' && argsMatch[1] !== 'seq' && argsMatch[1] !== 'obj') {
                            item.insertText = new vscode.SnippetString(`${name}($1)`);
                        } else item.insertText = name; 
                        completionItems.push(item);
                    }
                    return completionItems; 
                }

                // 2. Test Completions (Triggered by 'is ')
                if (/\s+is\s+[a-zA-Z0-9_]*$/.test(linePrefix)) {
                    for (const [name, info] of Object.entries(BUILTIN_TESTS)) {
                        const item = new vscode.CompletionItem(name, vscode.CompletionItemKind.TypeParameter);
                        item.detail = `Jinja Test: ${info.signature}`;
                        item.documentation = new vscode.MarkdownString(info.description);
                        completionItems.push(item);
                    }
                    return completionItems;
                }

                // 3. Tag Completions (Triggered by '{% ')
                const tagMatch = linePrefix.match(/\{%\s+([a-zA-Z0-9_]*)$/);
                if (tagMatch) {
                    const currentWord = tagMatch[1];
                    const lineText = document.lineAt(position.line).text;
                    const afterCursor = lineText.substring(position.character);
                    
                    // Smart cursor positioning post-completion
                    let endPosition = position;
                    if (afterCursor.startsWith(' %}')) endPosition = position.translate(0, 3);
                    else if (afterCursor.startsWith('%}')) endPosition = position.translate(0, 2);
                    else if (afterCursor.startsWith('}')) endPosition = position.translate(0, 1);

                    for (const [name, info] of Object.entries(BUILTIN_TAGS)) {
                        const item = new vscode.CompletionItem(name, vscode.CompletionItemKind.Keyword);
                        item.detail = `Jinja Tag`;
                        item.documentation = new vscode.MarkdownString(`**Syntax**: \`${info.syntax}\`\n\n${info.description}\n\n*💡 Caveat: ${info.caveat}*`);
                        const startPos = position.translate(0, -currentWord.length);
                        item.range = new vscode.Range(startPos, endPosition);
                        item.insertText = new vscode.SnippetString(info.snippet);
                        completionItems.push(item);
                    }
                    return completionItems;
                }

                // 4. Variable and Property Completions
                const inJinjaContextMatch = linePrefix.match(/(?:\{\{|\{%)[^{}%]*$/);
                if (inJinjaContextMatch) {
                    const jinjaText = inJinjaContextMatch[0]; 

                    const mergedContext = buildStrictContext(document, position);

                    // Handle Nested Property Access (e.g., user.profile.)
                    const propMatch = jinjaText.match(/([a-zA-Z0-9_]+(?:\.[a-zA-Z0-9_]+)*)\.([a-zA-Z0-9_]*)$/);
                    if (propMatch) {
                        const basePath = propMatch[1];
                        const parts = basePath.split('.');
                        let currentLevel = mergedContext;
                        
                        for (const part of parts) {
                            if (currentLevel && typeof currentLevel === 'object' && part in currentLevel) {
                                currentLevel = currentLevel[part];
                            } else {
                                currentLevel = undefined; break;
                            }
                        }

                        if (currentLevel && typeof currentLevel === 'object') {
                            for (const [key, val] of Object.entries(currentLevel)) {
                                // Filter out internal metadata keys
                                if (['__type__', 'def_line', 'args', 'signature', '__is_iterable__', '__element__'].includes(key)) continue; 
                                
                                const isCallable = (val as any)?.__type__ === 'Function' || (val as any)?.__type__ === 'Macro';
                                const kind = isCallable ? vscode.CompletionItemKind.Method : vscode.CompletionItemKind.Property;
                                const item = new vscode.CompletionItem(key, kind);
                                item.detail = `OmniJinja: ${getDisplayType(val)}`;
                                
                                // Auto-inject parenthesis for callable properties
                                if (isCallable) {
                                    const methodVal = val as any;
                                    if (methodVal.args && Array.isArray(methodVal.args)) {
                                        if (methodVal.args.length > 0) {
                                            const snippetArgs = methodVal.args.map((arg: string, index: number) => `\${${index + 1}:${arg}}`).join(', ');
                                            item.insertText = new vscode.SnippetString(`${key}(${snippetArgs})`);
                                        } else item.insertText = new vscode.SnippetString(`${key}()$0`);
                                    }
                                } else item.insertText = key;
                                completionItems.push(item);
                            }
                        }
                        
                        return completionItems; 
                    } 
                    
                    // Handle Base Variable Access (e.g., user)
                    const isDoubleBraceVar = linePrefix.match(/\{\{.*?([a-zA-Z0-9_]*)$/);
                    const isTagVar = linePrefix.match(/\{%\s+[a-zA-Z0-9_]+\s+.*?([a-zA-Z0-9_]*)$/);
                    const rootMatch = isDoubleBraceVar || isTagVar;

                    if (rootMatch) {
                        for (const [varName, varInfo] of Object.entries(mergedContext)) {
                            const isCallable = (varInfo as any)?.__type__ === 'Function' || (varInfo as any)?.__type__ === 'Macro';
                            const kind = isCallable ? vscode.CompletionItemKind.Function : vscode.CompletionItemKind.Variable;
                            const item = new vscode.CompletionItem(varName, kind);
                            item.detail = `OmniJinja: ${getDisplayType(varInfo)}`;
                            
                            if (isCallable && (varInfo as any).args) {
                                const argsList = (varInfo as any).args as string[];
                                const snippetArgs = argsList.map((arg: string, index: number) => `\${${index + 1}:${arg}}`).join(', ');
                                item.insertText = new vscode.SnippetString(`${varName}(${snippetArgs})`);
                            }
                            completionItems.push(item);
                        }
                        
                        // Inject Built-in Globals
                        for (const [name, info] of Object.entries(BUILTIN_GLOBALS)) {
                            const item = new vscode.CompletionItem(name, vscode.CompletionItemKind.Class);
                            item.detail = `Built-in Global: ${info.signature}`;
                            item.documentation = new vscode.MarkdownString(info.description);
                            if (info.snippet) item.insertText = new vscode.SnippetString(info.snippet);
                            else item.insertText = name;
                            completionItems.push(item);
                        }
                        return completionItems;
                    }
                    return undefined;
                }
                
                return undefined;
            }
        },
        '{', ' ', '|', '.', 's' // Trigger characters
    );

    const templatePathProvider = vscode.languages.registerCompletionItemProvider(
        supportedLanguages,
        {
            provideCompletionItems(document, position) {
                const linePrefix = document.lineAt(position).text.substr(0, position.character);
                // Trigger only inside 'extends' or 'include' quotes
                const pathMatch = linePrefix.match(/\{%\s*(?:extends|include)\s+['"]([^'"]*)$/);
                if (pathMatch) {
                    const completionItems: vscode.CompletionItem[] = [];
                    const uniquePaths = new Set<string>();
                    
                    for (const paths of templateFilesRegistry.values()) {
                        for (const p of paths) uniquePaths.add(p);
                    }
                    
                    for (const templatePath of uniquePaths) {
                        const item = new vscode.CompletionItem(templatePath, vscode.CompletionItemKind.File);
                        item.detail = "Jinja Template";
                        item.insertText = templatePath;
                        completionItems.push(item);
                    }
                    return completionItems;
                }
                return undefined;
            }
        },
        '"', "'" 
    );

    const hoverProvider = vscode.languages.registerHoverProvider(
        supportedLanguages,
        {
            provideHover(document, position) {
                const wordRange = document.getWordRangeAtPosition(position);
                if (!wordRange) return undefined;
                const hoveredWord = document.getText(wordRange);
                const lineText = document.lineAt(position.line).text;
                const textUpToHover = lineText.substring(0, wordRange.end.character);

                // Check standard built-ins first
                if (BUILTIN_TAGS[hoveredWord]) return createBuiltinHover('tag', BUILTIN_TAGS[hoveredWord].syntax, BUILTIN_TAGS[hoveredWord].description, BUILTIN_TAGS[hoveredWord].caveat);
                if (BUILTIN_FILTERS[hoveredWord]) return createBuiltinHover('filter', BUILTIN_FILTERS[hoveredWord].signature, BUILTIN_FILTERS[hoveredWord].description, BUILTIN_FILTERS[hoveredWord].caveat);
                if (BUILTIN_TESTS[hoveredWord]) return createBuiltinHover('test', BUILTIN_TESTS[hoveredWord].signature, BUILTIN_TESTS[hoveredWord].description);
                if (BUILTIN_GLOBALS[hoveredWord]) return createBuiltinHover('global', BUILTIN_GLOBALS[hoveredWord].signature, BUILTIN_GLOBALS[hoveredWord].description);

                // Check custom Python filters
                for (const [pyPath, filters] of filterRegistry.entries()) {
                    const foundFilter = filters.find((f: any) => f.name === hoveredWord);
                    if (foundFilter) {
                        const md = new vscode.MarkdownString();
                        md.appendCodeblock(`(filter) ${foundFilter.signature}`, 'python');
                        if (foundFilter.docstring) md.appendMarkdown(`\n---\n${foundFilter.docstring}`);
                        return new vscode.Hover(md);
                    }
                }

                const mergedContext = buildStrictContext(document, position);

                let foundValue: any = undefined;
                
                // Attempt precise path matching first (e.g., user.profile)
                const pathMatch = textUpToHover.match(/([a-zA-Z0-9_]+(?:\.[a-zA-Z0-9_]+)*)$/);
                if (pathMatch) {
                    const fullPath = pathMatch[1];
                    const parts = fullPath.split('.');
                    let currentLevel = mergedContext;
                    let validPath = true;
                    for (const part of parts) {
                        if (currentLevel && typeof currentLevel === 'object' && part in currentLevel) {
                            currentLevel = currentLevel[part];
                        } else {
                            validPath = false; break;
                        }
                    }
                    if (validPath) foundValue = currentLevel;
                }

                // Fallback to deep recursive search if exact path fails
                if (!foundValue) {
                    const deepSearch = (obj: any) => {
                        if (!obj || typeof obj !== 'object') return;
                        if (obj[hoveredWord]) { foundValue = obj[hoveredWord]; return; }
                        for (const key in obj) {
                            if (!['__type__', 'def_line', 'args', 'signature', '__is_iterable__'].includes(key) && typeof obj[key] === 'object') {
                                deepSearch(obj[key]);
                                if (foundValue) return;
                            }
                        }
                    };
                    deepSearch(mergedContext);
                }

                if (foundValue) {
                    const md = new vscode.MarkdownString();
                    const typeStr = getDisplayType(foundValue);
                    
                    const isCallable = foundValue && typeof foundValue === 'object' && (foundValue.__type__ === 'Function' || foundValue.__type__ === 'Macro');
                    if (isCallable) {
                        const sig = foundValue.signature || `${hoveredWord}()`;
                        const label = foundValue.__type__ === 'Macro' ? 'macro' : 'method';
                        md.appendCodeblock(`(${label}) ${sig}`, 'python');
                        if (foundValue.docstring) md.appendMarkdown(`\n---\n${foundValue.docstring}`);
                    } else {
                        md.appendCodeblock(`(variable) ${hoveredWord}: ${typeStr}`, 'typescript');
                    }
                    return new vscode.Hover(md);
                }
                return undefined;
            }
        }
    );

    const signatureProvider = vscode.languages.registerSignatureHelpProvider(
        supportedLanguages,
        {
            provideSignatureHelp(document, position) {
                const linePrefix = document.lineAt(position).text.substring(0, position.character);
                
                // Process Custom Filters
                const filterMatch = linePrefix.match(/\|\s*([a-zA-Z0-9_]+)\s*\([^)]*$/);
                if (filterMatch) {
                    const funcName = filterMatch[1];
                    const argsString = filterMatch[0].substring(filterMatch[0].indexOf('(') + 1);
                    const activeParameterIndex = (argsString.match(/,/g) || []).length;

                    for (const filters of filterRegistry.values()) {
                        const filter = filters.find(f => f.name === funcName);
                        if (filter) {
                            const sigHelp = new vscode.SignatureHelp();
                            const sigInfo = new vscode.SignatureInformation(
                                filter.signature,
                                new vscode.MarkdownString(filter.docstring ? `**${filter.docstring}**` : '')
                            );
                            if (filter.args && Array.isArray(filter.args)) {
                                sigInfo.parameters = filter.args.map((argName: string) => new vscode.ParameterInformation(argName));
                            }
                            sigHelp.signatures = [sigInfo];
                            sigHelp.activeSignature = 0;
                            sigHelp.activeParameter = activeParameterIndex; 
                            return sigHelp;
                        }
                    }
                }

                // Process Methods and Macros
                const methodMatch = linePrefix.match(/([a-zA-Z0-9_]+(?:\.[a-zA-Z0-9_]+)*)\s*\([^)]*$/);
                if (methodMatch) {
                    const fullPath = methodMatch[1];
                    const parts = fullPath.split('.');
                    
                    const mergedContext = buildStrictContext(document, position);

                    let currentLevel = mergedContext;
                    for (const part of parts) {
                        if (currentLevel && typeof currentLevel === 'object' && part in currentLevel) {
                            currentLevel = currentLevel[part];
                        } else {
                            currentLevel = undefined; break;
                        }
                    }

                    const isCallable = currentLevel && (currentLevel.__type__ === 'Function' || currentLevel.__type__ === 'Macro');
                    if (isCallable) {
                        const sigHelp = new vscode.SignatureHelp();
                        const sigInfo = new vscode.SignatureInformation(
                            currentLevel.signature || `${parts[parts.length-1]}()`,
                            new vscode.MarkdownString(currentLevel.docstring ? `**${currentLevel.docstring}**` : '')
                        );
                        if (currentLevel.args && Array.isArray(currentLevel.args)) {
                            sigInfo.parameters = currentLevel.args.map((argName: string) => new vscode.ParameterInformation(argName));
                        }
                        
                        const argsString = methodMatch[0].substring(methodMatch[0].indexOf('(') + 1);
                        const activeParameterIndex = (argsString.match(/,/g) || []).length;

                        sigHelp.signatures = [sigInfo];
                        sigHelp.activeSignature = 0;
                        sigHelp.activeParameter = activeParameterIndex;
                        return sigHelp;
                    }
                }
                return undefined;
            }
        },
        '(', ',' 
    );

    const definitionProvider = vscode.languages.registerDefinitionProvider(
        supportedLanguages,
        {
            provideDefinition(document, position) {
                const wordRange = document.getWordRangeAtPosition(position);
                if (!wordRange) return undefined;
                const word = document.getText(wordRange);

                // Look up definitions for Custom Filters
                for (const [pyPath, filters] of filterRegistry.entries()) {
                    const targetFilter = filters.find(f => f.name === word);
                    if (targetFilter) {
                        const lineNum = targetFilter.line ? targetFilter.line - 1 : 0;
                        return new vscode.Location(vscode.Uri.file(pyPath), new vscode.Position(lineNum, 0));
                    }
                }

                // Look up definitions for Context Variables
                const currentHtmlName = path.basename(document.fileName);
                const pySourcesMap = templateRegistry.get(currentHtmlName);
                if (pySourcesMap) {
                    for (const [pyPath, contextData] of pySourcesMap.entries()) {
                        let found = false;
                        let targetLine = 0; 
                        
                        const pathMatch = document.lineAt(position.line).text.substring(0, wordRange.end.character).match(/([a-zA-Z0-9_]+(?:\.[a-zA-Z0-9_]+)*)$/);
                        if (pathMatch) {
                            const fullPath = pathMatch[1];
                            const parts = fullPath.split('.');
                            let currentLevel = contextData;
                            let validPath = true;
                            for (const part of parts) {
                                if (currentLevel && typeof currentLevel === 'object' && part in currentLevel) {
                                    currentLevel = currentLevel[part];
                                } else {
                                    validPath = false; break;
                                }
                            }
                            if (validPath) {
                                found = true;
                                if (currentLevel) targetLine = (currentLevel.def_line || 1) - 1;
                            }
                        }

                        if (!found) {
                            const deepSearch = (obj: any) => {
                                if (!obj || typeof obj !== 'object') return;
                                if (word in obj) { 
                                    found = true; 
                                    const targetObj = obj[word];
                                    if (targetObj && typeof targetObj === 'object') {
                                        const rawLine = targetObj.def_line || targetObj.line;
                                        if (rawLine) targetLine = rawLine - 1; 
                                    }
                                    return; 
                                }
                                for (const key in obj) {
                                    if (!['__type__', 'def_line', 'args', 'signature', '__is_iterable__'].includes(key) && typeof obj[key] === 'object') {
                                        deepSearch(obj[key]);
                                        if (found) return;
                                    }
                                }
                            };
                            deepSearch(contextData);
                        }
                        if (found) return new vscode.Location(vscode.Uri.file(pyPath), new vscode.Position(targetLine, 0));
                    }
                }
                return undefined;
            }
        }
    );

    context.subscriptions.push(
        pyChangeListener, 
        htmlChangeListener, 
        watcher, 
        htmlWatcher,
        completionProvider, 
        hoverProvider, 
        signatureProvider, 
        definitionProvider, 
        templatePathProvider
    );
}

// ==========================================
// Subprocess Execution & Data Loading
// ==========================================

/**
 * Triggers the Python parsing script asynchronously for queued .py files.
 */
async function processQueue(enginePath: string, workspaceRoot: string) {
    if (isParsing || parseQueue.length === 0) return;
    isParsing = true;

    while (parseQueue.length > 0) {
        const filePath = parseQueue.shift()!; 
        const scriptPath = path.join(enginePath, 'main_py_parser.py');
        const command = `${activePythonCmd} "${scriptPath}" "${filePath}" "${workspaceRoot}"`;

        const doc = vscode.workspace.textDocuments.find(d => d.uri.fsPath === filePath);
        const content = doc ? doc.getText() : fs.readFileSync(filePath, 'utf-8');

        try {
            await new Promise((resolve, reject) => {
                const child = exec(command, (error, stdout) => {
                    if (error) reject(error);
                    else resolve(stdout);
                });
                if (child.stdin) {
                    child.stdin.write(content);
                    child.stdin.end();
                }
            });
            loadSchemaIntoMemory(filePath, workspaceRoot);
        } catch (e) {
            console.error(`Python Backend Parsing Error: ${filePath}`, e);
        }
    }
    isParsing = false; 
}

/**
 * Triggers the Jinja syntax detection script asynchronously for queued templates.
 */
async function processJinjaQueue(enginePath: string, workspaceRoot: string) {
    if (isJinjaParsing || jinjaParseQueue.length === 0) return;
    isJinjaParsing = true;

    while (jinjaParseQueue.length > 0) {
        const filePath = jinjaParseQueue.shift()!; 
        const scriptPath = path.join(enginePath, 'main_jinja_parser.py');
        const command = `${activePythonCmd} "${scriptPath}" "${filePath}" "${workspaceRoot}"`;
        const doc = vscode.workspace.textDocuments.find(d => d.uri.fsPath === filePath);
        const content = doc ? doc.getText() : fs.readFileSync(filePath, 'utf-8');

        try {
            await new Promise((resolve, reject) => {
                const child = exec(command, (error, stdout) => {
                    if (error) reject(error);
                    else resolve(stdout);
                });
                if (child.stdin) {
                    child.stdin.write(content);
                    child.stdin.end();
                }
            });
            loadJinjaSchemaIntoMemory(filePath, workspaceRoot);
        } catch (e) {
            console.error(`Jinja Syntax Parsing Error: ${filePath}`, e);
        }
    }
    isJinjaParsing = false; 
}

/**
 * Reads the generated _schema.json file and updates the in-memory registries.
 */
function loadSchemaIntoMemory(pyFilePath: string, workspaceRoot: string) {
    const baseName = path.basename(pyFilePath);
    const safeName = baseName + "_schema.json";
    const jsonPath = path.join(workspaceRoot, 'output_schemas', safeName);

    if (!fs.existsSync(jsonPath)) return;

    try {
        const schemaData = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
        
        if (schemaData.render_calls) {
            // Save raw calls for data flow validation
            renderCallRegistry.set(pyFilePath, schemaData.render_calls);

            for (const call of schemaData.render_calls) {
                const templateName = path.basename(call.template);
                if (!templateRegistry.has(templateName)) {
                    templateRegistry.set(templateName, new Map<string, any>());
                }
                templateRegistry.get(templateName)!.set(pyFilePath, call.context);
            }

            // TRIGGER VALIDATION: Python changed, re-validate supply against existing demand
            validateDataFlow(pyFilePath);
        } else {
            renderCallRegistry.delete(pyFilePath);
            pyDiagnosticCollection.delete(vscode.Uri.file(pyFilePath));
        }

        if (schemaData.custom_filters && schemaData.custom_filters.length > 0) {
            filterRegistry.set(pyFilePath, schemaData.custom_filters);
        } else {
            filterRegistry.delete(pyFilePath);
        }

        if (schemaData.template_files && Array.isArray(schemaData.template_files) && schemaData.template_files.length > 0) {
            templateFilesRegistry.set(pyFilePath, new Set(schemaData.template_files));
        } else {
            templateFilesRegistry.delete(pyFilePath);
        }

    } catch (e) {
        console.error("Failed to load backend JSON schema", e);
    }
}

/**
 * Reads the generated _jinja.json file, applies wavy underline diagnostics, 
 * and caches the repaired code for Quick Fixes.
 */
function loadJinjaSchemaIntoMemory(htmlFilePath: string, workspaceRoot: string) {
    const baseName = path.basename(htmlFilePath);
    const safeName = baseName + "_jinja.json"; 
    const jsonPath = path.join(workspaceRoot, 'jinja_schemas', safeName);

    if (!fs.existsSync(jsonPath)) {
        diagnosticCollection.delete(vscode.Uri.file(htmlFilePath));
        return;
    }

    try {
        const data = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
        
        const internalData = {};
        if (data.internal_variables) {
            Object.assign(internalData, data.internal_variables);
        }
        if (data.macros) {
            Object.assign(internalData, data.macros);
        }
        
        internalJinjaRegistry.set(baseName, internalData);

        if (data.fixed_code) {
            fixedCodeRegistry.set(htmlFilePath, data.fixed_code);
        } else {
            fixedCodeRegistry.delete(htmlFilePath);
        }

        // Extract and store External Requirements (Demand)
        if (data.external_requirements) {
            externalRequirementsRegistry.set(baseName, data.external_requirements);
            
            // TRIGGER VALIDATION: HTML changed, re-validate all Python files that supply this template
            const pySourcesMap = templateRegistry.get(baseName);
            if (pySourcesMap) {
                for (const pyPath of pySourcesMap.keys()) {
                    validateDataFlow(pyPath);
                }
            }
        } else {
            externalRequirementsRegistry.delete(baseName);
        }

        if (data.diagnostics && Array.isArray(data.diagnostics)) {
            const diagnostics: vscode.Diagnostic[] = [];
            
            // Check if this HTML template is rendered by any known Python file
            const isLinked = templateRegistry.has(baseName) && templateRegistry.get(baseName)!.size > 0;

            for (const diag of data.diagnostics) {
                // Suppress "Undefined" warnings if the template is not linked to any Python backend yet
                const isUndefinedWarning = diag.message && diag.message.toLowerCase().includes('undefined');
                if (!isLinked && isUndefinedWarning) {
                    continue; // Skip pushing this diagnostic
                }

                const lineNum = Math.max(0, (diag.line || 1) - 1);
                
                let colNum = 0;
                let length = 1000; 
                
                if (diag.col) {
                    colNum = Math.max(0, diag.col - 1);
                    length = diag.original ? String(diag.original).length : 5;
                }
                
                const range = new vscode.Range(lineNum, colNum, lineNum, colNum + length);
                const severity = diag.severity === 'error' ? vscode.DiagnosticSeverity.Error : vscode.DiagnosticSeverity.Warning;
                
                const diagnostic = new vscode.Diagnostic(range, diag.message, severity);
                diagnostic.source = 'OmniJinja';
                diagnostics.push(diagnostic);
            }
            diagnosticCollection.set(vscode.Uri.file(htmlFilePath), diagnostics);
        } else {
            diagnosticCollection.delete(vscode.Uri.file(htmlFilePath));
        }

    } catch (e) {
        console.error(`Failed to load Jinja JSON schema: ${safeName}`, e);
    }
}


// ==========================================
// Cross-File Data Flow Validation Engine
// ==========================================

/**
 * Validates a specific Python file by comparing its provided context (Supply)
 * against the external requirements (Demand) of the HTML templates it renders.
 */
function validateDataFlow(pyFilePath: string) {
    const calls = renderCallRegistry.get(pyFilePath);
    if (!calls) return;

    const diagnostics: vscode.Diagnostic[] = [];

    for (const call of calls) {
        const templateName = path.basename(call.template);
        const demand = externalRequirementsRegistry.get(templateName);
        
        if (!demand) continue; 

        const supply = call.context || {};
        const lineNum = Math.max(0, (call.render_line || 1) - 1);

        for (const [reqKey, reqVal] of Object.entries(demand)) {
            if (!(reqKey in supply)) {
                // ROOT MISSING -> Warning
                const range = new vscode.Range(lineNum, 0, lineNum, 50); // Highlight start of line
                diagnostics.push(new vscode.Diagnostic(
                    range, 
                    `OmniJinja [DataFlow]: Template '${templateName}' requires variable '${reqKey}' which is not provided in render_template.`, 
                    vscode.DiagnosticSeverity.Warning
                ));
            } else {
                // INITIATE DEEP CHECK
                checkDeep(reqKey, reqVal, supply[reqKey], templateName, lineNum, diagnostics);
            }
        }
    }
    
    // Publish diagnostics to the Python file
    pyDiagnosticCollection.set(vscode.Uri.file(pyFilePath), diagnostics);
}

/**
 * Recursively checks properties, callables, and iterables.
 */
function checkDeep(pathStr: string, demandNode: any, supplyNode: any, templateName: string, lineNum: number, diagnostics: vscode.Diagnostic[]) {
    if (!demandNode || typeof demandNode !== 'object') return;

    // 1. Behavior Check: Callable Mismatch -> Error
    if (demandNode.__is_callable__) {
        const sType = supplyNode?.__type__;
        if (sType && sType !== 'Function' && sType !== 'Method' && sType !== 'Macro' && sType !== 'Any') {
            const range = new vscode.Range(lineNum, 0, lineNum, 50);
            diagnostics.push(new vscode.Diagnostic(
                range, 
                `OmniJinja [DataFlow]: '${pathStr}' is called as a function in '${templateName}', but Python provides type '${sType}'.`, 
                vscode.DiagnosticSeverity.Error
            ));
        }
    }

    // 2. Behavior Check: Iterable Mismatch -> Error
    if (demandNode.__is_iterable__) {
        const sType = supplyNode?.__type__;
        const isIterable = supplyNode?.__is_iterable__;
        if (sType && !isIterable && sType !== 'Iterable' && sType !== 'List' && sType !== 'Tuple' && sType !== 'Dict' && sType !== 'Any') {
            const range = new vscode.Range(lineNum, 0, lineNum, 50);
            diagnostics.push(new vscode.Diagnostic(
                range, 
                `OmniJinja [DataFlow]: '${pathStr}' is iterated over in '${templateName}', but Python provides type '${sType}'.`, 
                vscode.DiagnosticSeverity.Error
            ));
        }
    }

    // 3. Deep Property Check -> Warning (Because Python dynamic nature might hide properties)
    for (const [key, val] of Object.entries(demandNode)) {
        if (key.startsWith('__')) continue; // Skip metadata keys

        if (!supplyNode || typeof supplyNode !== 'object' || !(key in supplyNode)) {
            const range = new vscode.Range(lineNum, 0, lineNum, 50);
            diagnostics.push(new vscode.Diagnostic(
                range, 
                `OmniJinja [DataFlow]: Template '${templateName}' expects property '${pathStr}.${key}', which might be missing in the provided context.`, 
                vscode.DiagnosticSeverity.Warning
            ));
        } else {
            checkDeep(`${pathStr}.${key}`, val, supplyNode[key], templateName, lineNum, diagnostics);
        }
    }
}

export function deactivate() {}